/** Canonical v0.6 status enum (matches `scripts/spec_validate.py`). */
export const VALID_STATUSES = new Set([
  "draft",
  "proposed",
  "approved",
  "pending",
  "running",
  "completed",
  "blocked",
  "failed",
  "cancelled",
]);

export const VALID_VBRIEF_VERSIONS = new Set(["0.6"]);

export const SPECIFICATION_NARRATIVE_KEY_ORDER = [
  "Overview",
  "ProblemStatement",
  "Goals",
  "UserStories",
  "Requirements",
  "SuccessMetrics",
  "EdgeCases",
  "Architecture",
  "TechDecisions",
  "ImplementationPhases",
  "PreImplementationGates",
] as const;

export const LIFECYCLE_BUCKETS: ReadonlyArray<readonly [string, string]> = [
  ["pending", "Pending"],
  ["active", "Active"],
  ["completed", "Completed"],
];

export const SPEC_RENDER_BANNER =
  "<!-- AUTO-GENERATED by task spec:render -- DO NOT EDIT MANUALLY -->\n" +
  "<!-- Purpose: rendered specification -->\n" +
  "<!-- Source of truth: vbrief/specification.vbrief.json -->\n" +
  "<!-- Regenerate with: task spec:render -->\n";

export const PRD_NARRATIVE_KEY_ORDER = [
  "Overview",
  "ProblemStatement",
  "Goals",
  "UserStories",
  "Requirements",
  "SuccessMetrics",
  "Architecture",
] as const;

export const PRD_BANNER =
  "<!-- AUTO-GENERATED by task prd:render -- DO NOT EDIT MANUALLY -->\n" +
  "<!-- Purpose: rendered PRD -->\n" +
  "<!-- Source of truth: vbrief/specification.vbrief.json -->\n" +
  "<!-- Regenerate with: task prd:render -->\n";

export const PRD_GENERATED_SENTINEL = "AUTO-GENERATED by task prd:render";

/** Max completed scopes listed under ## Completed in ROADMAP.md (#2653). */
export const ROADMAP_COMPLETED_CAP = 25;

/**
 * Shown when completed/ has history but pending/, active/, and proposed/ are empty.
 * Prevents silent Completed-only output without documenting empty-forward (#2653 D2.2).
 */
export const ROADMAP_EMPTY_FORWARD_MARKER =
  "_No open work in `pending/`, `active/`, or `proposed/`. " +
  "ROADMAP is an orientation view — use `task triage:queue` or plan-sequence for work selection._\n";

export const ROADMAP_BANNER =
  "<!-- AUTO-GENERATED by task roadmap:render -- DO NOT EDIT MANUALLY -->\n" +
  "<!-- Purpose: rendered roadmap -->\n" +
  "<!-- Source of truth: xbrief|vbrief pending/ + proposed/ + active/ (forward); completed/ capped -->\n" +
  "<!-- Regenerate with: task roadmap:render -->\n";

export const MIGRATOR_METADATA_KEY = "x-migrator";

export const PROJECT_LIFECYCLE_FOLDERS = [
  "proposed",
  "pending",
  "active",
  "completed",
  "cancelled",
] as const;

export const SKELETON_NARRATIVES: Readonly<Record<string, string>> = {
  Overview: "",
  "tech stack": "",
  Architecture: "",
  RisksAndUnknowns: "",
  Configuration: "",
};

export const SCOPE_SUMMARY_NARRATIVES = [
  "Overview",
  "Summary",
  "Description",
  "ProblemStatement",
  "Problem",
  "Outcome",
] as const;

export const RENDERABLE_SPEC_STATUSES = new Set(["approved", "running", "completed"]);
