import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  formatFrameworkCommand,
  hasCommand,
  normalizeTaskSeparator,
  runFrameworkCommand,
} from "./framework-commands.js";
import { renderPrd } from "./prd-render.js";
import { renderProjectDefinition } from "./project-render.js";
import { generateRoadmapContent } from "./roadmap-render.js";
import { renderSpec } from "./spec-render.js";
import { validateSpec } from "./spec-validate.js";

const MINIMAL_SPEC = {
  vBRIEFInfo: { version: "0.6" },
  plan: {
    title: "Test Spec",
    status: "approved",
    narratives: { Overview: "Overview body" },
    items: [],
  },
};

describe("spec-validate", () => {
  it("accepts valid vBRIEF", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sv-"));
    const path = join(dir, "spec.json");
    writeFileSync(path, JSON.stringify(MINIMAL_SPEC), "utf8");
    const [ok, msg] = validateSpec(path);
    expect(ok).toBe(true);
    expect(msg).toContain("valid vBRIEF");
    rmSync(dir, { recursive: true, force: true });
  });

  it("rejects missing file", () => {
    const [ok] = validateSpec("/nonexistent/spec.json");
    expect(ok).toBe(false);
  });

  it("rejects invalid version", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sv-bad-"));
    const path = join(dir, "spec.json");
    writeFileSync(
      path,
      JSON.stringify({
        vBRIEFInfo: { version: "0.5" },
        plan: { title: "T", status: "approved", items: [] },
      }),
      "utf8",
    );
    const [ok, msg] = validateSpec(path);
    expect(ok).toBe(false);
    expect(msg).toContain("0.6");
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("spec-render", () => {
  it("renders approved spec with banner and narratives", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-"));
    const vbrief = join(dir, "vbrief");
    mkdirSync(vbrief, { recursive: true });
    const specPath = join(vbrief, "specification.vbrief.json");
    const outPath = join(dir, "SPECIFICATION.md");
    writeFileSync(specPath, JSON.stringify(MINIMAL_SPEC), "utf8");
    const [ok] = renderSpec(specPath, outPath, { includeScopes: false });
    expect(ok).toBe(true);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("# Test Spec");
    expect(content).toContain("## Overview");
    expect(content).toContain("Overview body");
    rmSync(dir, { recursive: true, force: true });
  });

  it("rejects non-renderable status", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-draft-"));
    const specPath = join(dir, "spec.json");
    writeFileSync(
      specPath,
      JSON.stringify({ ...MINIMAL_SPEC, plan: { ...MINIMAL_SPEC.plan, status: "draft" } }),
      "utf8",
    );
    const [ok, msg] = renderSpec(specPath, join(dir, "out.md"));
    expect(ok).toBe(false);
    expect(msg).toContain("draft");
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("prd-render", () => {
  it("writes PRD with generated banner", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-prd-"));
    const specPath = join(dir, "spec.json");
    const outPath = join(dir, "PRD.md");
    writeFileSync(specPath, JSON.stringify(MINIMAL_SPEC), "utf8");
    renderPrd(specPath, outPath);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Product Requirements Document");
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("project-render", () => {
  it("creates skeleton PROJECT-DEFINITION", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-pr-"));
    const vbrief = join(dir, "vbrief");
    for (const f of ["proposed", "pending", "active", "completed", "cancelled"]) {
      mkdirSync(join(vbrief, f), { recursive: true });
    }
    const [ok, msg] = renderProjectDefinition(vbrief, { now: new Date("2026-06-04T12:00:00Z") });
    expect(ok).toBe(true);
    expect(msg).toContain("created");
    const content = readFileSync(join(vbrief, "PROJECT-DEFINITION.vbrief.json"), "utf8");
    expect(content).toContain('"version": "0.6"');
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("roadmap-render", () => {
  it("renders empty pending message", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-rr-"));
    const pending = join(dir, "vbrief", "pending");
    mkdirSync(pending, { recursive: true });
    const content = generateRoadmapContent(pending);
    expect(content).toContain("# Roadmap");
    expect(content).toContain("No pending work items.");
    rmSync(dir, { recursive: true, force: true });
  });

  it("groups flat scopes by phase", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-rr-phase-"));
    const pending = join(dir, "pending");
    mkdirSync(pending, { recursive: true });
    writeFileSync(
      join(pending, "2026-01-01-feature.vbrief.json"),
      JSON.stringify({
        vBRIEFInfo: { version: "0.6" },
        plan: {
          title: "Feature A",
          status: "pending",
          metadata: { "x-migrator": { Phase: "Phase 1", PhaseDescription: "Foundation" } },
          references: [{ uri: "https://github.com/o/r/issues/42" }],
        },
      }),
      "utf8",
    );
    const content = generateRoadmapContent(pending);
    expect(content).toContain("## Phase 1");
    expect(content).toContain("Foundation");
    expect(content).toContain("**#42**");
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("framework-commands", () => {
  it("formats deft surface", () => {
    expect(formatFrameworkCommand(["triage:welcome", "--onboard"])).toBe(
      "deft triage:welcome --onboard",
    );
  });

  it("normalizes task separator", () => {
    expect(normalizeTaskSeparator(["--", "--batch"])).toEqual(["--batch"]);
  });

  it("registers runtime commands", () => {
    for (const name of ["doctor", "triage:queue", "verify:cache-fresh", "check:consumer"]) {
      expect(hasCommand(name)).toBe(true);
    }
  });

  it("returns unknown command failure", () => {
    const result = runFrameworkCommand("__missing__", [], { capture: true });
    expect(result.code).toBe(2);
    expect(result.stderr).toContain("unknown framework command");
  });
});
