import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  formatFrameworkCommand,
  hasCommand,
  normalizeTaskSeparator,
  runFrameworkCommand,
} from "./framework-commands.js";
import { renderPrd } from "./prd-render.js";
import { renderProjectDefinition } from "./project-render.js";
import { generateRoadmapContent } from "./roadmap-render.js";
import { normalizeIncludeScopesMode, parseIncludeScopesFlag, renderSpec } from "./spec-render.js";
import { validateSpec } from "./spec-validate.js";

const MINIMAL_SPEC = {
  vBRIEFInfo: { version: "0.6" },
  plan: {
    title: "Test Spec",
    status: "approved",
    narratives: { Overview: "Overview body" },
    items: [],
  },
};

describe("spec-validate", () => {
  it("accepts valid vBRIEF", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sv-"));
    const path = join(dir, "spec.json");
    writeFileSync(path, JSON.stringify(MINIMAL_SPEC), "utf8");
    const [ok, msg] = validateSpec(path);
    expect(ok).toBe(true);
    expect(msg).toContain("valid vBRIEF");
    rmSync(dir, { recursive: true, force: true });
  });

  it("rejects missing file", () => {
    const [ok] = validateSpec("/nonexistent/spec.json");
    expect(ok).toBe(false);
  });

  it("rejects invalid version", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sv-bad-"));
    const path = join(dir, "spec.json");
    writeFileSync(
      path,
      JSON.stringify({
        vBRIEFInfo: { version: "0.5" },
        plan: { title: "T", status: "approved", items: [] },
      }),
      "utf8",
    );
    const [ok, msg] = validateSpec(path);
    expect(ok).toBe(false);
    expect(msg).toContain("0.6");
    rmSync(dir, { recursive: true, force: true });
  });
});

function writeScopeBrief(
  vbriefDir: string,
  folder: string,
  filename: string,
  plan: Record<string, unknown>,
): void {
  const dir = join(vbriefDir, folder);
  mkdirSync(dir, { recursive: true });
  writeFileSync(
    join(dir, filename),
    JSON.stringify({ xBRIEFInfo: { version: "0.8" }, plan }),
    "utf8",
  );
}

describe("spec-render", () => {
  it("renders approved spec with banner and narratives", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-"));
    const vbrief = join(dir, "xbrief");
    mkdirSync(vbrief, { recursive: true });
    const specPath = join(vbrief, "specification.xbrief.json");
    const outPath = join(dir, "SPECIFICATION.md");
    writeFileSync(specPath, JSON.stringify(MINIMAL_SPEC), "utf8");
    const [ok] = renderSpec(specPath, outPath, { includeScopes: false });
    expect(ok).toBe(true);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("# Test Spec");
    expect(content).toContain("## Overview");
    expect(content).toContain("Overview body");
    rmSync(dir, { recursive: true, force: true });
  });

  it("rejects non-renderable status", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-draft-"));
    const specPath = join(dir, "spec.json");
    writeFileSync(
      specPath,
      JSON.stringify({ ...MINIMAL_SPEC, plan: { ...MINIMAL_SPEC.plan, status: "draft" } }),
      "utf8",
    );
    const [ok, msg] = renderSpec(specPath, join(dir, "out.md"));
    expect(ok).toBe(false);
    expect(msg).toContain("draft");
    rmSync(dir, { recursive: true, force: true });
  });

  it("defaults to compact render: no Scope outlook and no LegacyArtifacts (#1566)", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-compact-"));
    const vbrief = join(dir, "xbrief");
    for (const folder of ["pending", "active", "completed"]) {
      mkdirSync(join(vbrief, folder), { recursive: true });
    }
    const specPath = join(vbrief, "specification.xbrief.json");
    writeFileSync(
      specPath,
      JSON.stringify({
        ...MINIMAL_SPEC,
        plan: {
          ...MINIMAL_SPEC.plan,
          narratives: {
            Overview: "Overview body",
            LegacyArtifacts: "Huge migration dump that must stay out by default.",
          },
        },
      }),
      "utf8",
    );
    writeScopeBrief(vbrief, "pending", "2026-01-01-pending.xbrief.json", {
      title: "Pending story",
      status: "pending",
      narratives: { Overview: "Pending overview" },
    });
    writeScopeBrief(vbrief, "active", "2026-01-02-active.xbrief.json", {
      title: "Active story",
      status: "running",
      narratives: { Overview: "Active overview" },
    });
    writeScopeBrief(vbrief, "completed", "2026-01-03-done.xbrief.json", {
      title: "Completed archive story",
      status: "completed",
      narratives: { Overview: "Completed archive that must not bloat default render" },
    });
    const outPath = join(dir, "SPECIFICATION.md");
    const [ok] = renderSpec(specPath, outPath);
    expect(ok).toBe(true);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("## Overview");
    expect(content).not.toContain("## Scope outlook");
    expect(content).not.toContain("Completed archive story");
    expect(content).not.toContain("## LegacyArtifacts");
    expect(content).not.toContain("Huge migration dump");
    for (const line of content.split("\n")) {
      expect(line).toBe(line.replace(/[ \t\u00a0]+$/u, ""));
    }
    rmSync(dir, { recursive: true, force: true });
  });

  it("include-scopes=current emits pending+active but not completed (#1566)", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-current-"));
    const vbrief = join(dir, "xbrief");
    for (const folder of ["pending", "active", "completed"]) {
      mkdirSync(join(vbrief, folder), { recursive: true });
    }
    const specPath = join(vbrief, "specification.xbrief.json");
    writeFileSync(specPath, JSON.stringify(MINIMAL_SPEC), "utf8");
    writeScopeBrief(vbrief, "pending", "2026-01-01-pending.xbrief.json", {
      title: "Pending story",
      status: "pending",
      narratives: { Overview: "Pending overview" },
    });
    writeScopeBrief(vbrief, "active", "2026-01-02-active.xbrief.json", {
      title: "Active story",
      status: "running",
      narratives: { Overview: "Active overview" },
    });
    writeScopeBrief(vbrief, "completed", "2026-01-03-done.xbrief.json", {
      title: "Completed archive story",
      status: "completed",
      narratives: { Overview: "Completed archive" },
    });
    const outPath = join(dir, "SPECIFICATION.md");
    const [ok] = renderSpec(specPath, outPath, { includeScopes: "current" });
    expect(ok).toBe(true);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("## Scope outlook");
    expect(content).toContain("Pending story");
    expect(content).toContain("Active story");
    expect(content).not.toContain("Completed archive story");
    expect(content).not.toContain("### Completed");
    rmSync(dir, { recursive: true, force: true });
  });

  it("include-scopes=all restores completed lifecycle aggregation (#1566)", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-all-"));
    const vbrief = join(dir, "xbrief");
    for (const folder of ["pending", "active", "completed"]) {
      mkdirSync(join(vbrief, folder), { recursive: true });
    }
    const specPath = join(vbrief, "specification.xbrief.json");
    writeFileSync(specPath, JSON.stringify(MINIMAL_SPEC), "utf8");
    writeScopeBrief(vbrief, "completed", "2026-01-03-done.xbrief.json", {
      title: "Completed archive story",
      status: "completed",
      narratives: { Overview: "Completed archive" },
    });
    const outPath = join(dir, "SPECIFICATION.md");
    const [ok] = renderSpec(specPath, outPath, { includeScopes: "all" });
    expect(ok).toBe(true);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("## Scope outlook");
    expect(content).toContain("Completed archive story");
    expect(content).toContain("### Completed");
    rmSync(dir, { recursive: true, force: true });
  });

  it("includeLegacyArtifacts=true emits LegacyArtifacts narrative (#1566)", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-legacy-"));
    const vbrief = join(dir, "xbrief");
    mkdirSync(vbrief, { recursive: true });
    const specPath = join(vbrief, "specification.xbrief.json");
    writeFileSync(
      specPath,
      JSON.stringify({
        ...MINIMAL_SPEC,
        plan: {
          ...MINIMAL_SPEC.plan,
          narratives: {
            Overview: "Overview body",
            LegacyArtifacts: "Preserved migration section",
          },
        },
      }),
      "utf8",
    );
    const outPath = join(dir, "SPECIFICATION.md");
    const [ok] = renderSpec(specPath, outPath, { includeLegacyArtifacts: true });
    expect(ok).toBe(true);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("## LegacyArtifacts");
    expect(content).toContain("Preserved migration section");
    rmSync(dir, { recursive: true, force: true });
  });

  it("parseIncludeScopesFlag defaults off and accepts modes (#1566)", () => {
    expect(parseIncludeScopesFlag(["spec.json"]).includeScopes).toBe("off");
    expect(parseIncludeScopesFlag(["--include-scopes=current", "spec.json"]).includeScopes).toBe(
      "current",
    );
    expect(parseIncludeScopesFlag(["--include-scopes", "spec.json"]).includeScopes).toBe("all");
    expect(
      parseIncludeScopesFlag(["--include-legacy-artifacts=on", "spec.json"]).includeLegacyArtifacts,
    ).toBe(true);
    expect(normalizeIncludeScopesMode(undefined)).toBe("off");
    expect(normalizeIncludeScopesMode(true)).toBe("all");
    expect(normalizeIncludeScopesMode("active")).toBe("current");
  });

  it("rejects mistyped include-scopes / legacy flags instead of silent omit (#1566)", () => {
    const badScopes = parseIncludeScopesFlag(["--include-scopes=curret", "spec.json"]);
    expect(badScopes.errors.length).toBe(1);
    expect(badScopes.errors[0]).toContain("Invalid --include-scopes=curret");
    const badLegacy = parseIncludeScopesFlag(["--include-legacy-artifacts=onn", "spec.json"]);
    expect(badLegacy.errors.length).toBe(1);
    expect(badLegacy.errors[0]).toContain("Invalid --include-legacy-artifacts=onn");
    expect(() => normalizeIncludeScopesMode("curret")).toThrow(/Invalid include-scopes/);
  });

  it("strips trailing whitespace from rendered markdown (#1566)", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-sr-ws-"));
    const vbrief = join(dir, "xbrief");
    mkdirSync(vbrief, { recursive: true });
    const specPath = join(vbrief, "specification.xbrief.json");
    writeFileSync(
      specPath,
      JSON.stringify({
        ...MINIMAL_SPEC,
        plan: {
          ...MINIMAL_SPEC.plan,
          narratives: {
            Overview: "Line with hard break  \nNext line   ",
          },
        },
      }),
      "utf8",
    );
    const outPath = join(dir, "SPECIFICATION.md");
    const [ok] = renderSpec(specPath, outPath);
    expect(ok).toBe(true);
    const content = readFileSync(outPath, "utf8");
    for (const line of content.split("\n")) {
      expect(line).toBe(line.replace(/[ \t\u00a0]+$/u, ""));
    }
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("prd-render", () => {
  it("writes PRD with generated banner", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-prd-"));
    const specPath = join(dir, "spec.json");
    const outPath = join(dir, "PRD.md");
    writeFileSync(specPath, JSON.stringify(MINIMAL_SPEC), "utf8");
    renderPrd(specPath, outPath);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Product Requirements Document");
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("project-render", () => {
  it("creates skeleton PROJECT-DEFINITION", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-pr-"));
    const vbrief = join(dir, "xbrief");
    for (const f of ["proposed", "pending", "active", "completed", "cancelled"]) {
      mkdirSync(join(vbrief, f), { recursive: true });
    }
    const [ok, msg] = renderProjectDefinition(vbrief, { now: new Date("2026-06-04T12:00:00Z") });
    expect(ok).toBe(true);
    expect(msg).toContain("created");
    const content = readFileSync(join(vbrief, "PROJECT-DEFINITION.xbrief.json"), "utf8");
    expect(content).toContain('"version": "0.8"');
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("roadmap-render", () => {
  it("renders empty pending message", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-rr-"));
    const pending = join(dir, "xbrief", "pending");
    mkdirSync(pending, { recursive: true });
    const content = generateRoadmapContent(pending);
    expect(content).toContain("# Roadmap");
    expect(content).toContain("No pending work items.");
    rmSync(dir, { recursive: true, force: true });
  });

  it("groups flat scopes by phase", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-rr-phase-"));
    const pending = join(dir, "pending");
    mkdirSync(pending, { recursive: true });
    writeFileSync(
      join(pending, "2026-01-01-feature.xbrief.json"),
      JSON.stringify({
        xBRIEFInfo: { version: "0.8" },
        plan: {
          title: "Feature A",
          status: "pending",
          metadata: { "x-migrator": { Phase: "Phase 1", PhaseDescription: "Foundation" } },
          references: [{ uri: "https://github.com/o/r/issues/42" }],
        },
      }),
      "utf8",
    );
    const content = generateRoadmapContent(pending);
    expect(content).toContain("## Phase 1");
    expect(content).toContain("Foundation");
    expect(content).toContain("**#42**");
    rmSync(dir, { recursive: true, force: true });
  });
});

describe("framework-commands", () => {
  it("formats deft surface", () => {
    expect(formatFrameworkCommand(["triage:welcome", "--onboard"])).toBe(
      "deft triage:welcome --onboard",
    );
  });

  it("normalizes task separator", () => {
    expect(normalizeTaskSeparator(["--", "--batch"])).toEqual(["--batch"]);
  });

  it("registers runtime commands", () => {
    for (const name of ["doctor", "triage:queue", "verify:cache-fresh", "check:consumer"]) {
      expect(hasCommand(name)).toBe(true);
    }
  });

  it("returns unknown command failure", () => {
    const result = runFrameworkCommand("__missing__", [], { capture: true });
    expect(result.code).toBe(2);
    expect(result.stderr).toContain("unknown framework command");
  });
});
