import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/** Repo root (deft framework checkout). */
export function repoRoot(): string {
  const here = fileURLToPath(new URL(".", import.meta.url));
  return resolve(here, "../../../../../");
}

export function readText(relPath: string): string {
  return readFileSync(join(repoRoot(), relPath), { encoding: "utf8" });
}

export function readAbs(absPath: string): string {
  return readFileSync(absPath, { encoding: "utf8" });
}

export function pathExists(relPath: string): boolean {
  return existsSync(join(repoRoot(), relPath));
}

export interface KnownFailure {
  check?: string;
  file?: string;
  composite_key?: string;
  xfail?: boolean;
  exempt?: boolean;
}

export function loadKnownFailures(): KnownFailure[] {
  const raw = readText("tests/content/snapshots/known_failures.json");
  return (JSON.parse(raw) as { known_failures: KnownFailure[] }).known_failures;
}

export function xfailFiles(check: string): Set<string> {
  return new Set(
    loadKnownFailures()
      .filter((e) => e.xfail && e.check === check && e.file)
      .map((e) => e.file as string),
  );
}

export function exemptFiles(check: string): Set<string> {
  return new Set(
    loadKnownFailures()
      .filter((e) => e.exempt && e.check === check && e.file)
      .map((e) => e.file as string),
  );
}

export function xfailComposite(check: string): Set<string> {
  return new Set(
    loadKnownFailures()
      .filter((e) => e.xfail && e.check === check && e.composite_key)
      .map((e) => e.composite_key as string),
  );
}

const SKIP_DIRS = new Set([
  ".git",
  ".venv",
  "__pycache__",
  ".pytest_cache",
  "backup",
  "dist",
  "tests",
  ".deft-cache",
]);

const MIGRATION_ARTIFACT_TREES = ["vbrief/migration"];

export function isMigrationArtifact(rel: string): boolean {
  if (MIGRATION_ARTIFACT_TREES.some((t) => rel.startsWith(`${t}/`))) {
    return true;
  }
  const name = rel.split("/").pop() ?? rel;
  return name.includes(".premigrate.");
}

/** All .md paths relative to repo root. */
export function allMdFiles(excludeTrees: string[] = []): string[] {
  const root = repoRoot();
  const result: string[] = [];

  function walk(dir: string): void {
    for (const ent of readdirSync(dir, { withFileTypes: true })) {
      if (SKIP_DIRS.has(ent.name)) {
        continue;
      }
      const abs = join(dir, ent.name);
      if (ent.isDirectory()) {
        walk(abs);
        continue;
      }
      if (!ent.name.endsWith(".md")) {
        continue;
      }
      const rel = relative(root, abs).split("\\").join("/");
      if (excludeTrees.some((t) => rel.startsWith(`${t}/`))) {
        continue;
      }
      if (isMigrationArtifact(rel)) {
        continue;
      }
      result.push(rel);
    }
  }

  walk(root);
  return result.sort();
}

export function mdFilesInDir(dirname: string): string[] {
  const dir = join(repoRoot(), dirname);
  if (!existsSync(dir)) {
    return [];
  }
  return readdirSync(dir)
    .filter((f) => f.endsWith(".md"))
    .map((f) => `${dirname}/${f}`)
    .sort();
}

export function contentAfterBanner(text: string): string {
  const lines = text.split("\n");
  let i = 0;
  if (i < lines.length && lines[i]?.startsWith("<!-- AUTO-GENERATED by task packs:render")) {
    while (i < lines.length && (lines[i]?.trim().startsWith("<!--") ?? false)) {
      i += 1;
    }
    while (i < lines.length && lines[i]?.trim() === "") {
      i += 1;
    }
  }
  return lines.slice(i).join("\n");
}

export function locateSection(text: string, heading: string): number {
  const anchored = `\n${heading}`;
  const idx = text.indexOf(anchored);
  if (idx < 0) {
    throw new Error(
      `section heading ${JSON.stringify(heading)} not found at newline-anchored position`,
    );
  }
  return idx + 1;
}

const LINK_RE = /\[[^\]]*\]\(([^)]+)\)/g;

export function internalLinks(relPath: string): Array<{ target: string; resolved: string }> {
  const root = repoRoot();
  const filePath = join(root, relPath);
  const text = readAbs(filePath);
  const parent = dirname(filePath);
  const results: Array<{ target: string; resolved: string }> = [];
  for (const m of text.matchAll(LINK_RE)) {
    const target = m[1] ?? "";
    if (
      target.startsWith("http://") ||
      target.startsWith("https://") ||
      target.startsWith("mailto:") ||
      target.startsWith("#")
    ) {
      continue;
    }
    const pathPart = target.split("#")[0]?.trim() ?? "";
    if (!pathPart) {
      continue;
    }
    results.push({ target, resolved: resolve(parent, pathPart) });
  }
  return results;
}

export function seeAlsoLinks(): Array<{ source: string; target: string; resolved: string }> {
  const root = repoRoot();
  const results: Array<{ source: string; target: string; resolved: string }> = [];
  for (const rel of allMdFiles()) {
    const filePath = join(root, rel);
    const text = readAbs(filePath);
    for (const line of text.split("\n")) {
      if (!line.toLowerCase().includes("see also")) {
        continue;
      }
      for (const m of line.matchAll(LINK_RE)) {
        const target = m[1] ?? "";
        if (
          target.startsWith("http://") ||
          target.startsWith("https://") ||
          target.startsWith("mailto:") ||
          target.startsWith("#")
        ) {
          continue;
        }
        const pathPart = target.split("#")[0]?.trim() ?? "";
        if (!pathPart) {
          continue;
        }
        results.push({ source: rel, target, resolved: resolve(dirname(filePath), pathPart) });
      }
    }
  }
  return results.sort((a, b) =>
    `${a.source}::${a.target}`.localeCompare(`${b.source}::${b.target}`),
  );
}

export function parseStrategyFilenames(): string[] {
  const readme = readText("strategies/README.md");
  const seen = new Set<string>();
  const result: string[] = [];
  for (const line of readme.split("\n")) {
    const stripped = line.trim();
    if (!stripped.startsWith("|")) {
      continue;
    }
    const cells = stripped.split("|");
    if (cells.length < 2) {
      continue;
    }
    const firstCell = cells[1]?.trim() ?? "";
    const match = firstCell.match(/\b([a-z][a-z0-9_-]*\.md)\b/);
    if (match?.[1] && !seen.has(match[1])) {
      seen.add(match[1]);
      result.push(match[1]);
    }
  }
  return result;
}

export function loadJson(relPath: string): unknown {
  return JSON.parse(readText(relPath));
}

export function isDir(relPath: string): boolean {
  try {
    return statSync(join(repoRoot(), relPath)).isDirectory();
  } catch {
    return false;
  }
}

export function isFile(relPath: string): boolean {
  try {
    return statSync(join(repoRoot(), relPath)).isFile();
  } catch {
    return false;
  }
}
