/** Port of scripts/pack_render.py — content-pack projection renderer (#1294, #1295). */

import { existsSync, lstatSync, mkdirSync, readFileSync, realpathSync } from "node:fs";
import { basename, dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { contentRoot } from "../content-root.js";
import { containedWrite } from "../fs/contained-write.js";

/** Write under the parent directory as containment root (#2980 wave D). */
function writeContainedFile(output: string, text: string): void {
  const abs = resolve(output);
  const dir = dirname(abs);
  mkdirSync(dir, { recursive: true });
  containedWrite({
    root: dir,
    target: basename(abs),
    data: text,
    mode: "replace",
  });
}

export function resolveRepoRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..", "..");
}

const REPO_ROOT = resolveRepoRoot();
const CONTENT_ROOT = contentRoot(REPO_ROOT);

export const DEFAULT_SOURCE = join(CONTENT_ROOT, "packs", "lessons", "lessons-pack-0.1.json");
export const DEFAULT_OUTPUT = join(REPO_ROOT, "meta", "lessons.md");

const LESSONS_BANNER: readonly string[] = [
  "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->",
  "<!-- Purpose: rendered lessons -->",
  "<!-- Source of truth: packs/lessons/lessons-pack-0.1.json -->",
  "<!-- Regenerate with: task packs:render -->",
  "<!-- Edit the source, not this file. Slice instead of loading the whole file: task packs:slice lessons <name> (e.g. recent --since, by-tag --tag) -->",
];

const SKILLS_BANNER: readonly string[] = [
  "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->",
  "<!-- Purpose: rendered skill -->",
  "<!-- Source of truth: packs/skills/skills-pack-0.1.json -->",
  "<!-- Regenerate with: task packs:render -->",
  "<!-- Edit the source, not this file. Slice instead of loading every SKILL.md: task packs:slice skills by-trigger --trigger <kw> (or list) -->",
];

const RULES_BANNER: readonly string[] = [
  "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->",
  "<!-- Purpose: rendered coding rules -->",
  "<!-- Source of truth: packs/rules/rules-pack-0.1.json -->",
  "<!-- Regenerate with: task packs:render -->",
  "<!-- Edit the source, not this file. Slice instead of loading every coding doc: task packs:slice rules by-tier --tier <TIER> (or by-domain, list) -->",
];

const STRATEGIES_BANNER: readonly string[] = [
  "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->",
  "<!-- Purpose: rendered strategy -->",
  "<!-- Source of truth: packs/strategies/strategies-pack-0.1.json -->",
  "<!-- Regenerate with: task packs:render -->",
  "<!-- Edit the source, not this file. Slice instead of loading every strategy: task packs:slice strategies by-trigger --trigger <kw> (or list) -->",
];

const PATTERNS_BANNER: readonly string[] = [
  "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->",
  "<!-- Purpose: rendered pattern -->",
  "<!-- Source of truth: packs/patterns/patterns-pack-0.1.json -->",
  "<!-- Regenerate with: task packs:render -->",
  "<!-- Edit the source, not this file. Slice instead of loading every pattern: task packs:slice patterns by-trigger --trigger <kw> (or list) -->",
];

const SWARM_SPEC_BANNER: readonly string[] = [
  "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->",
  "<!-- Purpose: rendered swarm spec -->",
  "<!-- Source of truth: packs/swarm-spec/swarm-spec-pack-0.1.json -->",
  "<!-- Regenerate with: task packs:render -->",
  "<!-- Edit the source, not this file. Slice instead of loading the whole spec: task packs:slice swarm-spec list -->",
];

export const BANNER = `${LESSONS_BANNER.join("\n")}\n`;
export const DOC_TITLE = "# Lessons Learned";

export interface RenderRegistryEntry {
  readonly mode: "collection" | "documents";
  readonly source: string;
  readonly output?: string;
  readonly items_field: string;
  readonly heading_field?: string;
  readonly body_field: string;
  readonly title?: string;
  readonly banner: readonly string[];
  readonly doc_kind?: "skill" | "markdown";
  readonly name_field?: string;
  readonly description_field?: string;
  readonly path_field?: string;
  /**
   * Pack-schema path pattern (mirrors content/vbrief/schemas/<pack>-pack.schema.json
   * `path.pattern`). Enforced fail-closed before render so a malicious pack JSON
   * cannot smuggle an off-shape projection path. Refs #2914 / #2904.
   */
  readonly path_pattern?: RegExp;
}

/** Non-zero exit code for a pack-render containment / schema refusal. */
export const PACK_RENDER_REFUSED_EXIT_CODE = 2;

/**
 * Thrown, fail-closed, when a pack record's projection path escapes CONTENT_ROOT,
 * violates the pack path schema, or a frontmatter field carries an injection
 * payload (null byte / newline). Remediates AppSec finding skill-pack-supply-01
 * from tracker #2904. Refs #2914.
 */
export class PackRenderContainmentError extends Error {
  readonly pack: string;
  readonly field: string;
  readonly offendingValue: string;

  constructor(message: string, details: { pack: string; field: string; offendingValue: string }) {
    super(message);
    this.name = "PackRenderContainmentError";
    this.pack = details.pack;
    this.field = details.field;
    this.offendingValue = details.offendingValue;
  }
}

/**
 * Path-SEGMENT containment: is `child` equal to `parent` or nested under it?
 * Uses `path.relative` so `/foo` is NOT treated as containing `/foobar`
 * (mirrors deposit/contain.ts).
 */
function isContained(parent: string, child: string): boolean {
  if (parent === child) {
    return true;
  }
  const rel = relative(parent, child);
  return rel.length > 0 && !rel.startsWith("..") && !isAbsolute(rel);
}

/** realpath with a resolve() fallback when the path does not exist yet. */
function safeRealpath(p: string): string {
  try {
    return realpathSync(p);
  } catch {
    return resolve(p);
  }
}

/**
 * Defense-in-depth: walk each EXISTING component from CONTENT_ROOT down to the
 * resolved output and refuse any symlink that escapes CONTENT_ROOT. Mirrors the
 * realpath-anchored segment walk in deposit/contain.ts so a symlinked content
 * subtree cannot redirect a projection write outside the shippable-content root.
 */
function assertAncestorContained(
  packName: string,
  field: string,
  rawPath: string,
  rootReal: string,
  outPath: string,
): void {
  const rel = relative(rootReal, outPath);
  const segments = rel.split(/[\\/]+/).filter((segment) => segment.length > 0);
  let current = rootReal;
  for (const segment of segments) {
    current = join(current, segment);
    let info: ReturnType<typeof lstatSync>;
    try {
      info = lstatSync(current);
    } catch {
      // Component does not exist yet; nothing below it can exist either.
      break;
    }
    if (info.isSymbolicLink()) {
      let linkReal: string;
      try {
        linkReal = realpathSync(current);
      } catch {
        throw new PackRenderContainmentError(
          `pack-render refused: ${packName} ${field} path component ${current} is a broken symlink`,
          { pack: packName, field, offendingValue: rawPath },
        );
      }
      if (!isContained(rootReal, linkReal)) {
        throw new PackRenderContainmentError(
          `pack-render refused: ${packName} ${field} path component ${current} is a symlink ` +
            `escaping CONTENT_ROOT (resolves to ${linkReal}, outside ${rootReal})`,
          { pack: packName, field, offendingValue: rawPath },
        );
      }
      current = linkReal;
    }
  }
}

/**
 * Resolve a pack record's projection path against CONTENT_ROOT and refuse,
 * fail-closed, any value that: is missing/empty/non-string, carries a null
 * byte, is absolute, violates the pack's schema path pattern, or resolves
 * outside CONTENT_ROOT (a `..` escape). Returns the contained absolute output
 * path. Mirrors deposit/contain.ts segment containment. Refs #2914 / #2904.
 */
export function containedOutPath(
  packName: string,
  rawPath: unknown,
  cfg: RenderRegistryEntry,
): string {
  const field = cfg.path_field ?? "path";
  if (typeof rawPath !== "string" || rawPath.length === 0) {
    throw new PackRenderContainmentError(
      `pack-render refused: ${packName} entry has a missing/empty ${field}`,
      { pack: packName, field, offendingValue: String(rawPath) },
    );
  }
  if (rawPath.includes("\0")) {
    throw new PackRenderContainmentError(
      `pack-render refused: ${packName} ${field} contains a null byte`,
      { pack: packName, field, offendingValue: rawPath },
    );
  }
  if (isAbsolute(rawPath) || /^[\\/]/.test(rawPath)) {
    throw new PackRenderContainmentError(
      `pack-render refused: ${packName} ${field} must be a relative path (got absolute ${JSON.stringify(rawPath)})`,
      { pack: packName, field, offendingValue: rawPath },
    );
  }
  if (cfg.path_pattern && !cfg.path_pattern.test(rawPath)) {
    throw new PackRenderContainmentError(
      `pack-render refused: ${packName} ${field} ${JSON.stringify(rawPath)} violates the ` +
        `${packName}-pack schema path pattern ${String(cfg.path_pattern)}`,
      { pack: packName, field, offendingValue: rawPath },
    );
  }
  // Resolve with realpath semantics on the trusted root, then confirm segment
  // containment. `resolve` collapses `..`, so an escape lands outside rootReal
  // and is refused here even when it slipped past the schema pattern (where `.`
  // can match a path separator).
  const rootReal = safeRealpath(CONTENT_ROOT);
  const outPath = resolve(rootReal, rawPath);
  if (!isContained(rootReal, outPath)) {
    throw new PackRenderContainmentError(
      `pack-render refused: ${packName} ${field} ${JSON.stringify(rawPath)} escapes CONTENT_ROOT ` +
        `(resolves to ${outPath}, outside ${rootReal})`,
      { pack: packName, field, offendingValue: rawPath },
    );
  }
  assertAncestorContained(packName, field, rawPath, rootReal, outPath);
  return outPath;
}

/** Refuse a frontmatter field value that embeds a null byte. Refs #2914. */
function assertNoNullByte(value: string, packName: string, field: string): string {
  if (value.includes("\0")) {
    throw new PackRenderContainmentError(
      `pack-render refused: ${packName} frontmatter field ${field} contains a null byte`,
      { pack: packName, field, offendingValue: value },
    );
  }
  return value;
}

/**
 * Sanitize a single-line YAML frontmatter field (skill `name`): refuse null
 * bytes and any CR/LF. An unescaped newline would inject arbitrary YAML keys or
 * a premature `---` document break into the generated frontmatter. Refs #2914.
 */
function sanitizeSingleLineField(value: string, packName: string, field: string): string {
  assertNoNullByte(value, packName, field);
  if (/[\r\n]/.test(value)) {
    throw new PackRenderContainmentError(
      `pack-render refused: ${packName} frontmatter field ${field} must not contain a newline ` +
        `(YAML frontmatter injection)`,
      { pack: packName, field, offendingValue: value },
    );
  }
  return value;
}

export const RENDER_REGISTRY: Record<string, RenderRegistryEntry> = {
  lessons: {
    mode: "collection",
    source: join(CONTENT_ROOT, "packs", "lessons", "lessons-pack-0.1.json"),
    output: join(REPO_ROOT, "meta", "lessons.md"),
    items_field: "lessons",
    heading_field: "title",
    body_field: "body",
    title: DOC_TITLE,
    banner: LESSONS_BANNER,
  },
  skills: {
    mode: "documents",
    doc_kind: "skill",
    source: join(CONTENT_ROOT, "packs", "skills", "skills-pack-0.1.json"),
    items_field: "skills",
    name_field: "id",
    description_field: "description",
    path_field: "path",
    path_pattern: /^skills\/.+\/SKILL\.md$/,
    body_field: "body",
    banner: SKILLS_BANNER,
  },
  rules: {
    mode: "documents",
    doc_kind: "markdown",
    source: join(CONTENT_ROOT, "packs", "rules", "rules-pack-0.1.json"),
    items_field: "rules",
    path_field: "path",
    path_pattern: /^(?:coding\/.+\.md|AGENTS\.md|main\.md)$/,
    body_field: "body",
    banner: RULES_BANNER,
  },
  strategies: {
    mode: "documents",
    doc_kind: "markdown",
    source: join(CONTENT_ROOT, "packs", "strategies", "strategies-pack-0.1.json"),
    items_field: "strategies",
    path_field: "path",
    path_pattern: /^strategies\/.+\.md$/,
    body_field: "body",
    banner: STRATEGIES_BANNER,
  },
  patterns: {
    mode: "documents",
    doc_kind: "markdown",
    source: join(CONTENT_ROOT, "packs", "patterns", "patterns-pack-0.1.json"),
    items_field: "patterns",
    path_field: "path",
    path_pattern: /^patterns\/.+\.md$/,
    body_field: "body",
    banner: PATTERNS_BANNER,
  },
  "swarm-spec": {
    mode: "documents",
    doc_kind: "markdown",
    source: join(CONTENT_ROOT, "packs", "swarm-spec", "swarm-spec-pack-0.1.json"),
    items_field: "entries",
    path_field: "path",
    path_pattern: /^swarm\/.+\.md$/,
    body_field: "body",
    banner: SWARM_SPEC_BANNER,
  },
};

function bannerText(bannerLines: readonly string[]): string {
  return `${bannerLines.join("\n")}\n`;
}

/** Mirrors Python ``textwrap.wrap`` with width 76 and default break behavior. */
function textWrap(description: string, width = 76): string[] {
  if (description.length === 0) {
    return [];
  }
  const words = description.split(/\s+/).filter((w) => w.length > 0);
  if (words.length === 0) {
    return [];
  }
  const lines: string[] = [];
  let current = words[0] as string;
  for (let i = 1; i < words.length; i += 1) {
    const word = words[i] as string;
    if (current.length + 1 + word.length <= width) {
      current = `${current} ${word}`;
    } else {
      lines.push(current);
      current = word;
    }
  }
  lines.push(current);
  return lines;
}

export function renderCollection(pack: Record<string, unknown>, cfg: RenderRegistryEntry): string {
  const parts: string[] = [bannerText(cfg.banner), `\n${cfg.title ?? ""}\n`];
  const items = pack[cfg.items_field];
  if (Array.isArray(items)) {
    for (const entry of items) {
      if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
        continue;
      }
      const record = entry as Record<string, unknown>;
      const heading = record[cfg.heading_field ?? "title"];
      const body = record[cfg.body_field];
      parts.push(`\n## ${String(heading)}\n\n${String(body)}\n`);
    }
  }
  return parts.join("");
}

function emitDescription(description: string): string {
  const wrapped = textWrap(description, 76);
  const lines = ["description: >-"];
  const bodyLines = wrapped.length > 0 ? wrapped : [""];
  for (const line of bodyLines) {
    lines.push(`  ${line}`);
  }
  return lines.join("\n");
}

export function renderSkillDocument(
  entry: Record<string, unknown>,
  cfg: RenderRegistryEntry,
): string {
  // Sanitize every YAML frontmatter field so a malicious pack cannot inject
  // unescaped frontmatter (newline -> extra key / premature `---`) or a null
  // byte. Refs #2914 / #2904 (skill-pack-supply-01).
  const nameField = cfg.name_field ?? "id";
  const descriptionField = cfg.description_field ?? "description";
  const name = sanitizeSingleLineField(String(entry[nameField]), "skills", nameField);
  const description = assertNoNullByte(String(entry[descriptionField]), "skills", descriptionField);
  const body = entry[cfg.body_field] ?? "";
  const extra = entry.frontmatter_extra;
  const extraStr =
    typeof extra === "string" ? assertNoNullByte(extra, "skills", "frontmatter_extra") : "";
  const extraBlock = extraStr.length > 0 ? `${extraStr}\n` : "";
  const frontmatter = `---\nname: ${name}\n${emitDescription(description)}\n${extraBlock}---\n`;
  return `${frontmatter}${bannerText(cfg.banner)}\n${String(body)}`;
}

export function renderMarkdownDocument(
  entry: Record<string, unknown>,
  cfg: RenderRegistryEntry,
): string {
  const body = entry[cfg.body_field] ?? "";
  return `${bannerText(cfg.banner)}\n${String(body)}`;
}

const DOCUMENT_RENDERERS: Record<
  string,
  (entry: Record<string, unknown>, cfg: RenderRegistryEntry) => string
> = {
  skill: renderSkillDocument,
  markdown: renderMarkdownDocument,
};

export function targetsForPack(
  packName: string,
  pack: Record<string, unknown>,
  cfg: RenderRegistryEntry,
): Array<[string, string]> {
  if (cfg.mode === "collection") {
    return [[cfg.output ?? "", renderCollection(pack, cfg)]];
  }
  const docRenderer = DOCUMENT_RENDERERS[cfg.doc_kind ?? "skill"] ?? renderSkillDocument;
  const targets: Array<[string, string]> = [];
  const items = pack[cfg.items_field];
  if (!Array.isArray(items)) {
    return targets;
  }
  for (const entry of items) {
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
      continue;
    }
    const record = entry as Record<string, unknown>;
    if (!record[cfg.body_field]) {
      continue;
    }
    const pathField = cfg.path_field ?? "path";
    // Document projection targets (skills/rules/strategies/patterns) are
    // shippable content -- they live under content/ in the source repo (#1875).
    // #2914: contain the pack-supplied path under CONTENT_ROOT and enforce the
    // pack schema path pattern BEFORE render so a malicious pack JSON cannot
    // write outside content/ via an absolute / `..` / null-byte path.
    const outPath = containedOutPath(packName, record[pathField], cfg);
    targets.push([outPath, docRenderer(record, cfg)]);
  }
  return targets;
}

export function collectTargets(packFilter?: string | null): Array<[string, string, string]> {
  const targets: Array<[string, string, string]> = [];
  for (const [name, cfg] of Object.entries(RENDER_REGISTRY)) {
    if (packFilter !== undefined && packFilter !== null && name !== packFilter) {
      continue;
    }
    if (!existsSync(cfg.source)) {
      throw new Error(`pack source not found: ${cfg.source}`);
    }
    const pack = JSON.parse(readFileSync(cfg.source, "utf8")) as Record<string, unknown>;
    for (const [outPath, text] of targetsForPack(name, pack, cfg)) {
      targets.push([name, outPath, text]);
    }
  }
  return targets;
}

export function render(pack: Record<string, unknown>): string {
  return renderCollection(pack, RENDER_REGISTRY.lessons as RenderRegistryEntry);
}

export function renderFile(source: string): string {
  if (!existsSync(source)) {
    throw new Error(`pack source not found: ${source}`);
  }
  const pack = JSON.parse(readFileSync(source, "utf8")) as Record<string, unknown>;
  return render(pack);
}

export function writeRender(source: string, output: string): string {
  const text = renderFile(source);
  // #2980 wave D: product write sink routes through containedWrite.
  writeContainedFile(output, text);
  return text;
}

export function checkDrift(source: string, output: string): [boolean, string, string] {
  const rendered = renderFile(source);
  const current = existsSync(output) ? readFileSync(output, "utf8") : "";
  return [rendered !== current, rendered, current];
}

function firstDiffLine(rendered: string, current: string): number {
  const rLines = rendered.split(/\r?\n/);
  const cLines = current.split(/\r?\n/);
  const limit = Math.min(rLines.length, cLines.length);
  for (let i = 0; i < limit; i += 1) {
    if (rLines[i] !== cLines[i]) {
      return i + 1;
    }
  }
  if (rLines.length !== cLines.length) {
    return Math.min(rLines.length, cLines.length) + 1;
  }
  return 0;
}

function runLegacy(source: string, output: string, check: boolean): number {
  if (check) {
    const [hasDrift, rendered, current] = checkDrift(source, output);
    if (hasDrift) {
      const line = firstDiffLine(rendered, current);
      process.stderr.write(
        `pack-drift: ${output} is out of sync with ${source} ` +
          `(first difference near line ${line}). ` +
          "Run `task packs:render` to regenerate.\n",
      );
      return 1;
    }
    process.stdout.write(`pack-drift: ${output} is in sync with ${source}.\n`);
    return 0;
  }
  writeRender(source, output);
  process.stdout.write(`Rendered ${output} from ${source}\n`);
  return 0;
}

function runMultipack(packFilter: string | null, check: boolean): number {
  const targets = collectTargets(packFilter);
  if (check) {
    const drifted: string[] = [];
    for (const [_name, outPath, text] of targets) {
      const current = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
      if (text !== current) {
        drifted.push(outPath);
      }
    }
    if (drifted.length > 0) {
      const listing = drifted.join(", ");
      process.stderr.write(
        `pack-drift: ${drifted.length} projection(s) out of sync: ${listing}. ` +
          "Run `task packs:render` to regenerate.\n",
      );
      return 1;
    }
    process.stdout.write(`pack-drift: all ${targets.length} projection(s) in sync.\n`);
    return 0;
  }
  // #2980 wave D: product write sinks route through containedWrite.
  for (const [_name, outPath, text] of targets) {
    writeContainedFile(outPath, text);
  }
  process.stdout.write(
    `Rendered ${targets.length} projection(s) across ${Object.keys(RENDER_REGISTRY).length} pack(s).\n`,
  );
  return 0;
}

interface ParsedArgs {
  source: string | null;
  output: string | null;
  pack: string | null;
  check: boolean;
}

function parseArgs(argv: string[]): ParsedArgs {
  const parsed: ParsedArgs = {
    source: null,
    output: null,
    pack: null,
    check: false,
  };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i] as string;
    if (arg === "--check") {
      parsed.check = true;
    } else if (arg === "--source") {
      parsed.source = argv[i + 1] ?? null;
      i += 1;
    } else if (arg.startsWith("--source=")) {
      parsed.source = arg.slice("--source=".length);
    } else if (arg === "--output") {
      parsed.output = argv[i + 1] ?? null;
      i += 1;
    } else if (arg.startsWith("--output=")) {
      parsed.output = arg.slice("--output=".length);
    } else if (arg === "--pack") {
      parsed.pack = argv[i + 1] ?? null;
      i += 1;
    } else if (arg.startsWith("--pack=")) {
      parsed.pack = arg.slice("--pack=".length);
    }
  }
  return parsed;
}

export function main(argv?: string[]): number {
  const args = parseArgs(argv ?? process.argv.slice(2));
  try {
    if (args.source !== null || args.output !== null) {
      const source = args.source ?? DEFAULT_SOURCE;
      const output = args.output ?? DEFAULT_OUTPUT;
      return runLegacy(source, output, args.check);
    }
    return runMultipack(args.pack, args.check);
  } catch (exc) {
    const message = exc instanceof Error ? exc.message : String(exc);
    process.stderr.write(`error: ${message}\n`);
    return 1;
  }
}
