import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { contentRoot } from "../content-root.js";
import {
  checkDrift,
  collectTargets,
  containedOutPath,
  DEFAULT_SOURCE,
  main,
  PackRenderContainmentError,
  RENDER_REGISTRY,
  render,
  renderCollection,
  renderFile,
  renderMarkdownDocument,
  renderSkillDocument,
  targetsForPack,
  writeRender,
} from "./pack-render.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..", "..", "..");
// #1875: pack sources + skill projections are shippable content (content/ in
// source, flattened in a consumer deposit). The lessons output (meta/lessons.md)
// is a repo-root-resident projection and stays at REPO_ROOT.
const CONTENT_ROOT = contentRoot(REPO_ROOT);
const REAL_SOURCE = join(CONTENT_ROOT, "packs", "lessons", "lessons-pack-0.1.json");
const REAL_OUTPUT = join(REPO_ROOT, "meta", "lessons.md");
const REAL_SKILLS_SOURCE = join(CONTENT_ROOT, "packs", "skills", "skills-pack-0.1.json");
const PROOF_SKILL_PATH = "skills/deft-directive-cost/SKILL.md";

describe("packRender.render", () => {
  it("includes banner and title", () => {
    const pack = JSON.parse(readFileSync(REAL_SOURCE, "utf8")) as Record<string, unknown>;
    const text = render(pack);
    const lines = text.split("\n");
    expect(lines[0]).toMatch(/AUTO-GENERATED by task packs:render/);
    expect(text).toContain("# Lessons Learned");
    expect(text).toContain("task packs:slice lessons");
  });

  it("renders entry shape", () => {
    const pack = {
      pack: "lessons-pack-0.1",
      version: "0.1",
      lessons: [
        { title: "Title One (2026-05)", body: "Body one." },
        { title: "Title Two (#7)", body: "Body two." },
      ],
    };
    const text = render(pack);
    expect(text).toContain("## Title One (2026-05)\n\nBody one.\n");
    expect(text).toContain("## Title Two (#7)\n\nBody two.\n");
  });

  it("round-trips committed projection", () => {
    const rendered = renderFile(REAL_SOURCE);
    const committed = readFileSync(REAL_OUTPUT, "utf8");
    expect(rendered).toBe(committed);
  });
});

describe("packRender.checkDrift", () => {
  it("reports clean on committed output", () => {
    const [hasDrift] = checkDrift(REAL_SOURCE, REAL_OUTPUT);
    expect(hasDrift).toBe(false);
  });

  it("detects divergence", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-drift-"));
    const out = join(root, "lessons.md");
    writeFileSync(out, "stale content\n", "utf8");
    const [hasDrift, rendered, current] = checkDrift(REAL_SOURCE, out);
    expect(hasDrift).toBe(true);
    expect(current).toBe("stale content\n");
    expect(rendered).not.toBe(current);
    rmSync(root, { recursive: true, force: true });
  });

  it("treats missing output as drift", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-miss-"));
    const [hasDrift, , current] = checkDrift(REAL_SOURCE, join(root, "absent.md"));
    expect(hasDrift).toBe(true);
    expect(current).toBe("");
    rmSync(root, { recursive: true, force: true });
  });
});

describe("packRender.writeRender", () => {
  it("creates nested output", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-write-"));
    const out = join(root, "nested", "lessons.md");
    const text = writeRender(REAL_SOURCE, out);
    expect(readFileSync(out, "utf8")).toBe(text);
    expect(text.startsWith("<!-- AUTO-GENERATED")).toBe(true);
    rmSync(root, { recursive: true, force: true });
  });

  it("raises when source missing", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-nosrc-"));
    expect(() => renderFile(join(root, "nope.json"))).toThrow(/pack source not found/);
    rmSync(root, { recursive: true, force: true });
  });
});

describe("packRender document modes", () => {
  it("renders skill document with folded description", () => {
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const text = renderSkillDocument(
      {
        id: "deft-alpha",
        description: "Alpha does things.",
        path: "skills/deft-alpha/SKILL.md",
        body: "# Alpha\n\nBody.\n",
      },
      cfg,
    );
    expect(text.split("\n")[1]).toBe("name: deft-alpha");
    expect(text).toContain("description: >-");
    expect(text.trimEnd().endsWith("Body.")).toBe(true);
  });

  it("round-trips proof skill", () => {
    const pack = JSON.parse(readFileSync(REAL_SKILLS_SOURCE, "utf8")) as Record<string, unknown>;
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const skills = pack.skills as Array<Record<string, unknown>>;
    const proof = skills.find((entry) => entry.path === PROOF_SKILL_PATH);
    expect(proof).toBeDefined();
    const rendered = renderSkillDocument(proof as Record<string, unknown>, cfg);
    const committed = readFileSync(join(CONTENT_ROOT, PROOF_SKILL_PATH), "utf8");
    expect(rendered).toBe(committed);
  });

  it("renders markdown document with banner separator", () => {
    const cfg = RENDER_REGISTRY.rules as NonNullable<(typeof RENDER_REGISTRY)["rules"]>;
    const text = renderMarkdownDocument({ body: "# Rule\n\nText." }, cfg);
    expect(text).toContain("<!-- Purpose: rendered coding rules -->");
    expect(text).toContain("# Rule\n\nText.");
  });

  it("renderCollection uses registry config", () => {
    const pack = { lessons: [{ title: "T", body: "B" }] };
    const text = renderCollection(
      pack,
      RENDER_REGISTRY.lessons as NonNullable<(typeof RENDER_REGISTRY)["lessons"]>,
    );
    expect(text).toContain("## T\n\nB\n");
  });

  it("renderCollection skips invalid lesson entries", () => {
    const cfg = RENDER_REGISTRY.lessons as NonNullable<(typeof RENDER_REGISTRY)["lessons"]>;
    const text = renderCollection(
      { lessons: [null, "bad", [], { title: "Ok", body: "Body" }] },
      cfg,
    );
    expect(text).toContain("## Ok\n\nBody\n");
    expect(text.match(/## Ok/g)?.length).toBe(1);
  });

  it("renderSkillDocument includes frontmatter_extra and long description wrap", () => {
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const longDesc = Array.from({ length: 30 }, (_, i) => `word${i}`).join(" ");
    const text = renderSkillDocument(
      {
        id: "deft-beta",
        description: longDesc,
        frontmatter_extra: "metadata: true",
        body: "# Beta\n",
      },
      cfg,
    );
    expect(text).toContain("metadata: true");
    expect(text.split("\n").some((line) => line.startsWith("  word"))).toBe(true);
  });

  it("renderSkillDocument handles empty description", () => {
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const text = renderSkillDocument({ id: "x", description: "", body: "body" }, cfg);
    expect(text).toContain("description: >-\n  \n");
  });
});

describe("packRender.collectTargets", () => {
  it("covers lessons and skills packs", () => {
    const targets = collectTargets();
    const names = new Set(targets.map(([name]) => name));
    expect(names.has("lessons")).toBe(true);
    expect(names.has("skills")).toBe(true);
  });

  it("filters to one pack", () => {
    const targets = collectTargets("skills");
    expect(new Set(targets.map(([name]) => name))).toEqual(new Set(["skills"]));
    expect(targets.every(([, path]) => path.endsWith("SKILL.md"))).toBe(true);
  });

  it("includes rules markdown projections", () => {
    const targets = collectTargets("rules");
    expect(targets.length).toBeGreaterThan(0);
    // Normalize separators for cross-platform path inclusion check.
    expect(
      targets.every(
        ([name, path]) => name === "rules" && path.replace(/\\/g, "/").includes("coding/"),
      ),
    ).toBe(true);
  });
});

describe("packRender.main", () => {
  it("legacy check mode clean on committed", () => {
    const stdout: string[] = [];
    const original = process.stdout.write.bind(process.stdout);
    process.stdout.write = ((chunk: string | Uint8Array) => {
      stdout.push(String(chunk));
      return true;
    }) as typeof process.stdout.write;
    try {
      expect(main(["--source", REAL_SOURCE, "--output", REAL_OUTPUT, "--check"])).toBe(0);
      expect(stdout.join("")).toContain("in sync");
    } finally {
      process.stdout.write = original;
    }
  });

  it("legacy check mode reports drift", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-main-"));
    const out = join(root, "lessons.md");
    writeFileSync(out, "stale\n", "utf8");
    const stderr: string[] = [];
    const original = process.stderr.write.bind(process.stderr);
    process.stderr.write = ((chunk: string | Uint8Array) => {
      stderr.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    try {
      expect(main(["--source", REAL_SOURCE, "--output", out, "--check"])).toBe(1);
      expect(stderr.join("")).toContain("pack-drift");
    } finally {
      process.stderr.write = original;
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("legacy write mode", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-mainw-"));
    const out = join(root, "lessons.md");
    expect(main(["--source", REAL_SOURCE, "--output", out])).toBe(0);
    expect(readFileSync(out, "utf8")).toBe(renderFile(REAL_SOURCE));
    rmSync(root, { recursive: true, force: true });
  });

  it("multipack check on committed projections", () => {
    const stdout: string[] = [];
    const original = process.stdout.write.bind(process.stdout);
    process.stdout.write = ((chunk: string | Uint8Array) => {
      stdout.push(String(chunk));
      return true;
    }) as typeof process.stdout.write;
    try {
      expect(main(["--check"])).toBe(0);
      expect(stdout.join("")).toContain("in sync");
    } finally {
      process.stdout.write = original;
    }
  });

  it("returns 1 when source missing", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-err-"));
    const stderr: string[] = [];
    const original = process.stderr.write.bind(process.stderr);
    process.stderr.write = ((chunk: string | Uint8Array) => {
      stderr.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    try {
      expect(main(["--source", join(root, "nope.json")])).toBe(1);
      expect(stderr.join("")).toContain("error:");
    } finally {
      process.stderr.write = original;
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("multipack write renders projections", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-mp-"));
    const source = join(root, "lessons-pack-0.1.json");
    const output = join(root, "out", "lessons.md");
    mkdirSync(join(root, "out"), { recursive: true });
    writeFileSync(source, readFileSync(REAL_SOURCE, "utf8"), "utf8");
    expect(main(["--source", source, "--output", output])).toBe(0);
    expect(readFileSync(output, "utf8")).toBe(renderFile(source));
    rmSync(root, { recursive: true, force: true });
  });

  it("parses equals-form flags and pack filter", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-eq-"));
    const out = join(root, "lessons.md");
    expect(main([`--source=${REAL_SOURCE}`, `--output=${out}`])).toBe(0);
    expect(readFileSync(out, "utf8")).toBe(renderFile(REAL_SOURCE));
    const stdout: string[] = [];
    const original = process.stdout.write.bind(process.stdout);
    process.stdout.write = ((chunk: string | Uint8Array) => {
      stdout.push(String(chunk));
      return true;
    }) as typeof process.stdout.write;
    try {
      expect(main(["--pack=lessons", "--check"])).toBe(0);
      expect(stdout.join("")).toContain("in sync");
    } finally {
      process.stdout.write = original;
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("multipack check reports drift across projections", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-mpdrift-"));
    const stale = join(root, "stale-lessons.md");
    writeFileSync(stale, "not the real projection\n", "utf8");
    const stderr: string[] = [];
    const originalErr = process.stderr.write.bind(process.stderr);
    process.stderr.write = ((chunk: string | Uint8Array) => {
      stderr.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    try {
      expect(main(["--source", REAL_SOURCE, "--output", stale, "--check"])).toBe(1);
      expect(stderr.join("")).toContain("first difference near line");
    } finally {
      process.stderr.write = originalErr;
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("packRender defaults", () => {
  it("exposes default source path", () => {
    expect(DEFAULT_SOURCE).toContain("lessons-pack-0.1.json");
  });
});

// #2914 / tracker #2904 (skill-pack-supply-01): pack-render must contain
// projection paths under CONTENT_ROOT, enforce pack schema path patterns, and
// refuse frontmatter injection -- all fail-closed.
describe("packRender.containedOutPath (#2914 path containment + schema)", () => {
  const skillsCfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
  const rulesCfg = RENDER_REGISTRY.rules as NonNullable<(typeof RENDER_REGISTRY)["rules"]>;

  it("returns a CONTENT_ROOT-contained path for a schema-valid entry", () => {
    const out = containedOutPath("skills", "skills/deft-alpha/SKILL.md", skillsCfg);
    expect(out.replace(/\\/g, "/")).toContain("skills/deft-alpha/SKILL.md");
    expect(out.startsWith(CONTENT_ROOT) || out.includes("content")).toBe(true);
  });

  it("refuses an absolute path (escape)", () => {
    expect(() => containedOutPath("skills", "/etc/cron.d/evil", skillsCfg)).toThrow(
      PackRenderContainmentError,
    );
    expect(() => containedOutPath("skills", "/etc/cron.d/evil", skillsCfg)).toThrow(
      /must be a relative path/,
    );
  });

  it("refuses a leading-slash / backslash path", () => {
    expect(() => containedOutPath("rules", "\\\\server\\share\\x.md", rulesCfg)).toThrow(
      PackRenderContainmentError,
    );
  });

  it("refuses a `../` traversal escape even if it satisfies the schema glob", () => {
    // `.+` in the schema pattern can match a separator, so the pattern alone is
    // insufficient; the resolved-containment check is the real guard.
    const evil = "skills/../../../../../../tmp/evil/SKILL.md";
    expect(skillsCfg.path_pattern?.test(evil)).toBe(true);
    expect(() => containedOutPath("skills", evil, skillsCfg)).toThrow(/escapes CONTENT_ROOT/);
  });

  it("refuses a null byte in the path", () => {
    expect(() => containedOutPath("skills", "skills/a\u0000b/SKILL.md", skillsCfg)).toThrow(
      /null byte/,
    );
  });

  it("refuses a path that violates the pack schema pattern", () => {
    expect(() => containedOutPath("skills", "notskills/x/SKILL.md", skillsCfg)).toThrow(
      /violates the skills-pack schema path pattern/,
    );
    expect(() => containedOutPath("rules", "secrets/passwd", rulesCfg)).toThrow(
      /violates the rules-pack schema path pattern/,
    );
  });

  it("refuses a missing / non-string path", () => {
    expect(() => containedOutPath("skills", undefined, skillsCfg)).toThrow(/missing\/empty/);
    expect(() => containedOutPath("skills", "", skillsCfg)).toThrow(/missing\/empty/);
    expect(() => containedOutPath("skills", 42, skillsCfg)).toThrow(/missing\/empty/);
  });
});

describe("packRender.targetsForPack refuses malicious pack entries (#2914)", () => {
  const skillsCfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;

  it("refuses render when any entry escapes CONTENT_ROOT", () => {
    const pack = {
      skills: [
        {
          id: "evil",
          description: "pwn",
          path: "skills/../../../../../../tmp/evil/SKILL.md",
          body: "# owned\n",
        },
      ],
    };
    expect(() => targetsForPack("skills", pack, skillsCfg)).toThrow(PackRenderContainmentError);
  });

  it("refuses render on an absolute path entry", () => {
    const pack = {
      skills: [{ id: "evil", description: "pwn", path: "/etc/evil/SKILL.md", body: "x" }],
    };
    expect(() => targetsForPack("skills", pack, skillsCfg)).toThrow(/must be a relative path/);
  });

  it("renders a well-formed entry to a contained path", () => {
    const pack = {
      skills: [
        { id: "deft-alpha", description: "ok", path: "skills/deft-alpha/SKILL.md", body: "# A\n" },
      ],
    };
    const targets = targetsForPack("skills", pack, skillsCfg);
    expect(targets.length).toBe(1);
    const [outPath, text] = targets[0] as [string, string];
    expect(outPath.replace(/\\/g, "/")).toContain("skills/deft-alpha/SKILL.md");
    expect(text).toContain("name: deft-alpha");
  });
});

describe("packRender.renderSkillDocument frontmatter sanitization (#2914)", () => {
  const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;

  it("refuses a newline in the skill name (YAML frontmatter injection)", () => {
    expect(() =>
      renderSkillDocument(
        { id: "evil\ninjected: true", description: "d", path: "skills/x/SKILL.md", body: "b" },
        cfg,
      ),
    ).toThrow(/must not contain a newline/);
  });

  it("refuses a null byte in the skill name", () => {
    expect(() => renderSkillDocument({ id: "a\u0000b", description: "d", body: "b" }, cfg)).toThrow(
      /null byte/,
    );
  });

  it("refuses a null byte in the description", () => {
    expect(() =>
      renderSkillDocument({ id: "ok", description: "d\u0000x", body: "b" }, cfg),
    ).toThrow(/null byte/);
  });

  it("refuses a null byte in frontmatter_extra", () => {
    expect(() =>
      renderSkillDocument(
        { id: "ok", description: "d", frontmatter_extra: "triggers:\u0000", body: "b" },
        cfg,
      ),
    ).toThrow(/null byte/);
  });

  it("still renders a clean entry unchanged", () => {
    const text = renderSkillDocument(
      { id: "deft-alpha", description: "Alpha does things.", body: "# Alpha\n" },
      cfg,
    );
    expect(text.split("\n")[1]).toBe("name: deft-alpha");
  });
});

describe("packRender.collectTargets stays contained on real packs (#2914)", () => {
  it("every real projection target resolves under CONTENT_ROOT or REPO_ROOT", () => {
    const targets = collectTargets();
    for (const [, outPath] of targets) {
      const norm = outPath.replace(/\\/g, "/");
      expect(norm.includes("..")).toBe(false);
    }
  });
});
