import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import {
  checkDrift,
  collectTargets,
  DEFAULT_SOURCE,
  main,
  RENDER_REGISTRY,
  render,
  renderCollection,
  renderFile,
  renderMarkdownDocument,
  renderSkillDocument,
  writeRender,
} from "./pack-render.js";

const REPO_ROOT = join(import.meta.dirname, "..", "..", "..", "..");
const REAL_SOURCE = join(REPO_ROOT, "packs", "lessons", "lessons-pack-0.1.json");
const REAL_OUTPUT = join(REPO_ROOT, "meta", "lessons.md");
const REAL_SKILLS_SOURCE = join(REPO_ROOT, "packs", "skills", "skills-pack-0.1.json");
const PROOF_SKILL_PATH = "skills/deft-directive-cost/SKILL.md";

describe("packRender.render", () => {
  it("includes banner and title", () => {
    const pack = JSON.parse(readFileSync(REAL_SOURCE, "utf8")) as Record<string, unknown>;
    const text = render(pack);
    const lines = text.split("\n");
    expect(lines[0]).toMatch(/AUTO-GENERATED by task packs:render/);
    expect(text).toContain("# Lessons Learned");
    expect(text).toContain("task packs:slice lessons");
  });

  it("renders entry shape", () => {
    const pack = {
      pack: "lessons-pack-0.1",
      version: "0.1",
      lessons: [
        { title: "Title One (2026-05)", body: "Body one." },
        { title: "Title Two (#7)", body: "Body two." },
      ],
    };
    const text = render(pack);
    expect(text).toContain("## Title One (2026-05)\n\nBody one.\n");
    expect(text).toContain("## Title Two (#7)\n\nBody two.\n");
  });

  it("round-trips committed projection", () => {
    const rendered = renderFile(REAL_SOURCE);
    const committed = readFileSync(REAL_OUTPUT, "utf8");
    expect(rendered).toBe(committed);
  });
});

describe("packRender.checkDrift", () => {
  it("reports clean on committed output", () => {
    const [hasDrift] = checkDrift(REAL_SOURCE, REAL_OUTPUT);
    expect(hasDrift).toBe(false);
  });

  it("detects divergence", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-drift-"));
    const out = join(root, "lessons.md");
    writeFileSync(out, "stale content\n", "utf8");
    const [hasDrift, rendered, current] = checkDrift(REAL_SOURCE, out);
    expect(hasDrift).toBe(true);
    expect(current).toBe("stale content\n");
    expect(rendered).not.toBe(current);
    rmSync(root, { recursive: true, force: true });
  });

  it("treats missing output as drift", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-miss-"));
    const [hasDrift, , current] = checkDrift(REAL_SOURCE, join(root, "absent.md"));
    expect(hasDrift).toBe(true);
    expect(current).toBe("");
    rmSync(root, { recursive: true, force: true });
  });
});

describe("packRender.writeRender", () => {
  it("creates nested output", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-write-"));
    const out = join(root, "nested", "lessons.md");
    const text = writeRender(REAL_SOURCE, out);
    expect(readFileSync(out, "utf8")).toBe(text);
    expect(text.startsWith("<!-- AUTO-GENERATED")).toBe(true);
    rmSync(root, { recursive: true, force: true });
  });

  it("raises when source missing", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-nosrc-"));
    expect(() => renderFile(join(root, "nope.json"))).toThrow(/pack source not found/);
    rmSync(root, { recursive: true, force: true });
  });
});

describe("packRender document modes", () => {
  it("renders skill document with folded description", () => {
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const text = renderSkillDocument(
      {
        id: "deft-alpha",
        description: "Alpha does things.",
        path: "skills/deft-alpha/SKILL.md",
        body: "# Alpha\n\nBody.\n",
      },
      cfg,
    );
    expect(text.split("\n")[1]).toBe("name: deft-alpha");
    expect(text).toContain("description: >-");
    expect(text.trimEnd().endsWith("Body.")).toBe(true);
  });

  it("round-trips proof skill", () => {
    const pack = JSON.parse(readFileSync(REAL_SKILLS_SOURCE, "utf8")) as Record<string, unknown>;
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const skills = pack.skills as Array<Record<string, unknown>>;
    const proof = skills.find((entry) => entry.path === PROOF_SKILL_PATH);
    expect(proof).toBeDefined();
    const rendered = renderSkillDocument(proof as Record<string, unknown>, cfg);
    const committed = readFileSync(join(REPO_ROOT, PROOF_SKILL_PATH), "utf8");
    expect(rendered).toBe(committed);
  });

  it("renders markdown document with banner separator", () => {
    const cfg = RENDER_REGISTRY.rules as NonNullable<(typeof RENDER_REGISTRY)["rules"]>;
    const text = renderMarkdownDocument({ body: "# Rule\n\nText." }, cfg);
    expect(text).toContain("<!-- Purpose: rendered coding rules -->");
    expect(text).toContain("# Rule\n\nText.");
  });

  it("renderCollection uses registry config", () => {
    const pack = { lessons: [{ title: "T", body: "B" }] };
    const text = renderCollection(
      pack,
      RENDER_REGISTRY.lessons as NonNullable<(typeof RENDER_REGISTRY)["lessons"]>,
    );
    expect(text).toContain("## T\n\nB\n");
  });

  it("renderCollection skips invalid lesson entries", () => {
    const cfg = RENDER_REGISTRY.lessons as NonNullable<(typeof RENDER_REGISTRY)["lessons"]>;
    const text = renderCollection(
      { lessons: [null, "bad", [], { title: "Ok", body: "Body" }] },
      cfg,
    );
    expect(text).toContain("## Ok\n\nBody\n");
    expect(text.match(/## Ok/g)?.length).toBe(1);
  });

  it("renderSkillDocument includes frontmatter_extra and long description wrap", () => {
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const longDesc = Array.from({ length: 30 }, (_, i) => `word${i}`).join(" ");
    const text = renderSkillDocument(
      {
        id: "deft-beta",
        description: longDesc,
        frontmatter_extra: "metadata: true",
        body: "# Beta\n",
      },
      cfg,
    );
    expect(text).toContain("metadata: true");
    expect(text.split("\n").some((line) => line.startsWith("  word"))).toBe(true);
  });

  it("renderSkillDocument handles empty description", () => {
    const cfg = RENDER_REGISTRY.skills as NonNullable<(typeof RENDER_REGISTRY)["skills"]>;
    const text = renderSkillDocument({ id: "x", description: "", body: "body" }, cfg);
    expect(text).toContain("description: >-\n  \n");
  });
});

describe("packRender.collectTargets", () => {
  it("covers lessons and skills packs", () => {
    const targets = collectTargets();
    const names = new Set(targets.map(([name]) => name));
    expect(names.has("lessons")).toBe(true);
    expect(names.has("skills")).toBe(true);
  });

  it("filters to one pack", () => {
    const targets = collectTargets("skills");
    expect(new Set(targets.map(([name]) => name))).toEqual(new Set(["skills"]));
    expect(targets.every(([, path]) => path.endsWith("SKILL.md"))).toBe(true);
  });

  it("includes rules markdown projections", () => {
    const targets = collectTargets("rules");
    expect(targets.length).toBeGreaterThan(0);
    expect(targets.every(([name, path]) => name === "rules" && path.includes("coding/"))).toBe(
      true,
    );
  });
});

describe("packRender.main", () => {
  it("legacy check mode clean on committed", () => {
    const stdout: string[] = [];
    const original = process.stdout.write.bind(process.stdout);
    process.stdout.write = ((chunk: string | Uint8Array) => {
      stdout.push(String(chunk));
      return true;
    }) as typeof process.stdout.write;
    try {
      expect(main(["--source", REAL_SOURCE, "--output", REAL_OUTPUT, "--check"])).toBe(0);
      expect(stdout.join("")).toContain("in sync");
    } finally {
      process.stdout.write = original;
    }
  });

  it("legacy check mode reports drift", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-main-"));
    const out = join(root, "lessons.md");
    writeFileSync(out, "stale\n", "utf8");
    const stderr: string[] = [];
    const original = process.stderr.write.bind(process.stderr);
    process.stderr.write = ((chunk: string | Uint8Array) => {
      stderr.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    try {
      expect(main(["--source", REAL_SOURCE, "--output", out, "--check"])).toBe(1);
      expect(stderr.join("")).toContain("pack-drift");
    } finally {
      process.stderr.write = original;
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("legacy write mode", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-mainw-"));
    const out = join(root, "lessons.md");
    expect(main(["--source", REAL_SOURCE, "--output", out])).toBe(0);
    expect(readFileSync(out, "utf8")).toBe(renderFile(REAL_SOURCE));
    rmSync(root, { recursive: true, force: true });
  });

  it("multipack check on committed projections", () => {
    const stdout: string[] = [];
    const original = process.stdout.write.bind(process.stdout);
    process.stdout.write = ((chunk: string | Uint8Array) => {
      stdout.push(String(chunk));
      return true;
    }) as typeof process.stdout.write;
    try {
      expect(main(["--check"])).toBe(0);
      expect(stdout.join("")).toContain("in sync");
    } finally {
      process.stdout.write = original;
    }
  });

  it("returns 1 when source missing", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-err-"));
    const stderr: string[] = [];
    const original = process.stderr.write.bind(process.stderr);
    process.stderr.write = ((chunk: string | Uint8Array) => {
      stderr.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    try {
      expect(main(["--source", join(root, "nope.json")])).toBe(1);
      expect(stderr.join("")).toContain("error:");
    } finally {
      process.stderr.write = original;
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("multipack write renders projections", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-mp-"));
    const source = join(root, "lessons-pack-0.1.json");
    const output = join(root, "out", "lessons.md");
    mkdirSync(join(root, "out"), { recursive: true });
    writeFileSync(source, readFileSync(REAL_SOURCE, "utf8"), "utf8");
    expect(main(["--source", source, "--output", output])).toBe(0);
    expect(readFileSync(output, "utf8")).toBe(renderFile(source));
    rmSync(root, { recursive: true, force: true });
  });

  it("parses equals-form flags and pack filter", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-eq-"));
    const out = join(root, "lessons.md");
    expect(main([`--source=${REAL_SOURCE}`, `--output=${out}`])).toBe(0);
    expect(readFileSync(out, "utf8")).toBe(renderFile(REAL_SOURCE));
    const stdout: string[] = [];
    const original = process.stdout.write.bind(process.stdout);
    process.stdout.write = ((chunk: string | Uint8Array) => {
      stdout.push(String(chunk));
      return true;
    }) as typeof process.stdout.write;
    try {
      expect(main(["--pack=lessons", "--check"])).toBe(0);
      expect(stdout.join("")).toContain("in sync");
    } finally {
      process.stdout.write = original;
      rmSync(root, { recursive: true, force: true });
    }
  });

  it("multipack check reports drift across projections", () => {
    const root = mkdtempSync(join(tmpdir(), "prender-mpdrift-"));
    const stale = join(root, "stale-lessons.md");
    writeFileSync(stale, "not the real projection\n", "utf8");
    const stderr: string[] = [];
    const originalErr = process.stderr.write.bind(process.stderr);
    process.stderr.write = ((chunk: string | Uint8Array) => {
      stderr.push(String(chunk));
      return true;
    }) as typeof process.stderr.write;
    try {
      expect(main(["--source", REAL_SOURCE, "--output", stale, "--check"])).toBe(1);
      expect(stderr.join("")).toContain("first difference near line");
    } finally {
      process.stderr.write = originalErr;
      rmSync(root, { recursive: true, force: true });
    }
  });
});

describe("packRender defaults", () => {
  it("exposes default source path", () => {
    expect(DEFAULT_SOURCE).toContain("lessons-pack-0.1.json");
  });
});
