import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { fileSha256 } from "./default-extractor.js";
import { markdownText, renderCodebaseMap, runCodebaseMapCli } from "./map.js";
import { selectCodebaseMap } from "./provider.js";

function writeProjectDefinition(root: string, policy?: Record<string, unknown>): void {
  mkdirSync(join(root, "vbrief"), { recursive: true });
  const plan: Record<string, unknown> = {
    title: "Fixture",
    status: "running",
    items: [],
    architecture: {
      codeStructure: {
        version: "0.1",
        modules: [
          {
            id: "app",
            name: "App",
            purpose: "Application entry points.",
            pathGlobs: ["app/**/*.py"],
          },
          {
            id: "lib",
            name: "Library",
            purpose: "Shared helpers.",
            pathGlobs: ["lib/**/*.py"],
          },
        ],
        pathOwnership: [],
        allowedPatterns: [],
        projectionManifest: [
          {
            path: ".planning/codebase/MAP.md",
            kind: "codebase-map",
            source: "plan.architecture.codeStructure",
            generated: true,
          },
        ],
      },
    },
  };
  if (policy !== undefined) {
    plan.policy = policy;
  }
  writeFileSync(
    join(root, "vbrief", "PROJECT-DEFINITION.vbrief.json"),
    JSON.stringify({ vBRIEFInfo: { version: "0.6" }, plan }),
    { encoding: "utf8" },
  );
}

function writeCode(root: string): void {
  mkdirSync(join(root, "app"));
  mkdirSync(join(root, "lib"));
  writeFileSync(join(root, "app", "main.py"), "from lib.util import thing\nthing()\n", {
    encoding: "utf8",
  });
  writeFileSync(join(root, "lib", "util.py"), "def thing():\n    return 1\n", {
    encoding: "utf8",
  });
}

function providerArtifact(root: string): Record<string, unknown> {
  const appPath = join(root, "app", "main.py");
  return {
    formatVersion: "codebase-map.v1",
    contractVersion: "codebase-provider.v1",
    kind: "codebase-map",
    provider: { name: "fixture-provider", version: "1.0" },
    source: {
      projectRoot: root,
      contentHashes: {
        algorithm: "sha256",
        files: [{ path: "app/main.py", sha256: fileSha256(appPath) }],
      },
    },
    modules: [
      {
        id: "provider-app",
        name: "Provider App",
        purpose: "Provider supplied app module.",
        pathGlobs: ["app/**/*.py"],
        fileCount: 1,
        files: ["app/main.py"],
        derivedFrom: { files: "provider", intent: "provider" },
      },
    ],
    coupling: [],
    entryPoints: [],
    languageDistribution: [{ language: "Python", files: 1, derivedFrom: "provider" }],
    degraded: [],
  };
}

describe("codebase MAP renderer", () => {
  it("renders projection sections", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-map-"));
    writeProjectDefinition(root);
    writeCode(root);
    const selection = selectCodebaseMap(root);

    const rendered = renderCodebaseMap(selection.artifact);

    expect(rendered).toContain("AUTO-GENERATED by task codebase:map");
    expect(rendered).toContain("Source of truth: vbrief/PROJECT-DEFINITION.vbrief.json");
    expect(rendered).toContain("| `app` | App | Application entry points.");
    expect(rendered).toContain("| `app` | `lib` | heuristic | app/main.py:1 imports lib.util |");
    expect(rendered).toContain("## Degraded Signals");
  });

  it("falls back to files length for malformed boolean fileCount", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-map-"));
    writeCode(root);
    const artifact = providerArtifact(root);
    (artifact.modules as Record<string, unknown>[])[0] = {
      ...((artifact.modules as Record<string, unknown>[])[0] ?? {}),
      fileCount: true,
      files: ["app/main.py", "app/extra.py"],
    };

    const rendered = renderCodebaseMap(artifact);

    expect(rendered).toContain("| `provider-app` | Provider App | Provider supplied app module.");
    expect(rendered).toContain(
      "| `provider-app` | Provider App | Provider supplied app module. | `app/**/*.py` | 2 |",
    );
  });

  it("writes projectionManifest output", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-map-"));
    writeProjectDefinition(root);
    writeCode(root);

    const result = runCodebaseMapCli(["--project-root", root]);

    expect(result.exitCode).toBe(0);
    const text = readFileSync(join(root, ".planning", "codebase", "MAP.md"), {
      encoding: "utf8",
    });
    expect(text).toContain("# Codebase MAP");
  });

  it("refuses to clobber hand-authored output before provider selection", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-map-"));
    writeProjectDefinition(root);
    writeCode(root);
    const output = join(root, ".planning", "codebase", "MAP.md");
    mkdirSync(join(root, ".planning", "codebase"), { recursive: true });
    writeFileSync(output, "# Hand-authored map\n", { encoding: "utf8" });

    const result = runCodebaseMapCli([
      "--project-root",
      root,
      "--generate-with",
      "definitely-missing-provider",
    ]);

    expect(result.exitCode).toBe(2);
    expect(readFileSync(output, { encoding: "utf8" })).toBe("# Hand-authored map\n");
  });

  it("uses policy provider artifact when fresh", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-map-"));
    writeCode(root);
    mkdirSync(join(root, ".planning", "codebase"), { recursive: true });
    writeFileSync(
      join(root, ".planning", "codebase", "provider-map.json"),
      JSON.stringify(providerArtifact(root)),
      { encoding: "utf8" },
    );
    writeProjectDefinition(root, {
      projectionProviders: {
        "codebase-map": {
          artifactPath: ".planning/codebase/provider-map.json",
          expect: { provider: "fixture-provider", version: "1.0" },
        },
      },
    });

    const result = runCodebaseMapCli(["--project-root", root]);

    expect(result.exitCode).toBe(0);
    const text = readFileSync(join(root, ".planning", "codebase", "MAP.md"), {
      encoding: "utf8",
    });
    expect(text).toContain("fixture-provider");
    expect(text).toContain("`provider-app`");
  });
});

describe("markdownText (CodeQL #50 backslash-first escaping)", () => {
  it("escapes the backslash escape character before the pipe delimiter", () => {
    // A pre-existing backslash must not be able to bypass the `|` escape.
    expect(markdownText("a\\|b")).toBe("a\\\\\\|b");
    expect(markdownText("c|d")).toBe("c\\|d");
    expect(markdownText("e\\f")).toBe("e\\\\f");
  });

  it("collapses newlines and trims, and handles nullish input", () => {
    expect(markdownText("line1\nline2")).toBe("line1 line2");
    expect(markdownText(null)).toBe("");
    expect(markdownText(undefined)).toBe("");
  });
});
