import { existsSync, readFileSync } from "node:fs";
import { isAbsolute, join, relative, resolve } from "node:path";
import { containedWrite } from "../fs/contained-write.js";
import { assertProjectionContained } from "../fs/projection-containment.js";
import { resolveProjectDefinitionPath } from "../layout/resolve.js";
import { extractCodeStructure, loadJsonFile } from "../verify-source/code-structure-validate.js";
import {
  CodeStructureConfigError,
  configErrorToDict,
  defaultCodeStructurePath,
} from "./default-extractor.js";
import { sortedStringifyPretty } from "./json.js";
import { CODEBASE_MAP_KIND } from "./projection-registry.js";
import { artifactSha256, selectCodebaseMap } from "./provider.js";

export const GENERATED_SENTINEL = "AUTO-GENERATED by task codebase:map";
export const DEFAULT_OUTPUT_PATH = ".planning/codebase/MAP.md";
export const BANNER_TEMPLATE =
  "<!-- AUTO-GENERATED by task codebase:map -- DO NOT EDIT MANUALLY -->\n" +
  "<!-- Purpose: generated codebase MAP projection -->\n" +
  "<!-- Source of truth: xbrief/PROJECT-DEFINITION.xbrief.json " +
  "plan.architecture.codeStructure -->\n" +
  "<!-- Regenerate with: task codebase:map -->\n";

export function markdownText(value: unknown): string {
  const text = value === null || value === undefined ? "" : String(value);
  // Escape the backslash escape character FIRST, then the `|` table delimiter.
  // Escaping `|` alone lets a pre-existing backslash bypass the delimiter
  // escape (CodeQL js/incomplete-sanitization).
  return text.replace(/\\/g, "\\\\").replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}

function code(value: unknown): string {
  const text = markdownText(value);
  if (text.length === 0) {
    return "";
  }
  return `\`${text.replace(/`/g, "")}\``;
}

function joinCode(values: unknown, limit?: number): string {
  if (!Array.isArray(values)) {
    return "";
  }
  let items = values.filter(
    (item): item is string => typeof item === "string" && item.trim().length > 0,
  );
  let truncated = false;
  if (limit !== undefined && items.length > limit) {
    items = items.slice(0, limit);
    truncated = true;
  }
  let rendered = items.map((item) => code(item)).join(", ");
  if (truncated) {
    rendered = `${rendered}, ...`;
  }
  return rendered;
}

function posixPath(path: string): string {
  return path.replace(/\\/g, "/");
}

function displayPath(pathValue: unknown, projectRootValue: unknown): string {
  if (typeof pathValue !== "string" || pathValue.length === 0) {
    return "";
  }
  if (typeof projectRootValue !== "string" || projectRootValue.length === 0) {
    return pathValue;
  }
  const rel = posixPath(relative(resolve(projectRootValue), resolve(pathValue)));
  if (rel === "" || rel.startsWith("../") || rel === ".." || isAbsolute(rel)) {
    return pathValue;
  }
  return rel;
}

function sourceDigest(artifact: Record<string, unknown>): string {
  const source = artifact.source;
  if (typeof source !== "object" || source === null || Array.isArray(source)) {
    return artifactSha256(artifact);
  }
  const contentHash = (source as Record<string, unknown>).contentHash;
  if (
    typeof contentHash === "object" &&
    contentHash !== null &&
    !Array.isArray(contentHash) &&
    typeof (contentHash as Record<string, unknown>).value === "string"
  ) {
    return String((contentHash as Record<string, unknown>).value);
  }
  return artifactSha256(artifact);
}

export function projectionOutputPath(projectRoot: string, explicitOutput?: string | null): string {
  if (explicitOutput !== undefined && explicitOutput !== null && explicitOutput.length > 0) {
    return explicitOutput;
  }

  const projectDefinition = resolveProjectDefinitionPath(projectRoot);
  if (!existsSync(projectDefinition)) {
    return DEFAULT_OUTPUT_PATH;
  }

  const data = loadJsonFile(projectDefinition);
  const extracted = extractCodeStructure(data);
  if (extracted === null) {
    return DEFAULT_OUTPUT_PATH;
  }
  const manifest = extracted.record.projectionManifest;
  if (!Array.isArray(manifest)) {
    return DEFAULT_OUTPUT_PATH;
  }
  for (const entry of manifest) {
    if (typeof entry !== "object" || entry === null || Array.isArray(entry)) {
      continue;
    }
    const rec = entry as Record<string, unknown>;
    if (rec.kind === CODEBASE_MAP_KIND && typeof rec.path === "string") {
      return rec.path;
    }
  }
  return DEFAULT_OUTPUT_PATH;
}

export function renderCodebaseMap(artifact: Record<string, unknown>): string {
  const source =
    typeof artifact.source === "object" &&
    artifact.source !== null &&
    !Array.isArray(artifact.source)
      ? (artifact.source as Record<string, unknown>)
      : {};
  const provider =
    typeof artifact.provider === "object" &&
    artifact.provider !== null &&
    !Array.isArray(artifact.provider)
      ? (artifact.provider as Record<string, unknown>)
      : {};
  const sourcePath = displayPath(source.codeStructurePath, source.projectRoot);
  const sourceHome = source.codeStructureHome || "directory-derived fallback";
  const artifactDigest = artifactSha256(artifact);
  const digest = sourceDigest(artifact);

  const lines = [
    BANNER_TEMPLATE.trimEnd(),
    `<!-- Artifact sha256: ${artifactDigest} -->`,
    `<!-- Source digest sha256: ${digest} -->`,
    "",
    "# Codebase MAP",
    "",
    "| Field | Value |",
    "| --- | --- |",
    `| Projection kind | ${code(artifact.kind)} |`,
    `| Format | ${code(artifact.formatVersion)} |`,
    `| Provider | ${code(provider.name)} ${code(provider.version)} |`,
    `| Provider mode | ${code(provider.mode)} |`,
    `| Source | ${code(sourcePath)} at ${code(sourceHome)} |`,
    `| Source digest | ${code(digest)} |`,
    "",
    "## Modules",
    "",
    "| Module | Name | Purpose | Paths | Files |",
    "| --- | --- | --- | --- | ---: |",
  ];

  const modules = Array.isArray(artifact.modules) ? artifact.modules : [];
  for (const module of modules) {
    if (typeof module !== "object" || module === null || Array.isArray(module)) {
      continue;
    }
    const rec = module as Record<string, unknown>;
    let fileCount = rec.fileCount;
    if (typeof fileCount !== "number" || !Number.isInteger(fileCount)) {
      const files = rec.files;
      fileCount = Array.isArray(files) ? files.length : 0;
    }
    lines.push(
      "| " +
        `${code(rec.id)} | ` +
        `${markdownText(rec.name)} | ` +
        `${markdownText(rec.purpose)} | ` +
        `${joinCode(rec.pathGlobs, 4)} | ` +
        `${fileCount} |`,
    );
  }

  lines.push("", "## Coupling", "");
  const coupling = Array.isArray(artifact.coupling)
    ? artifact.coupling.filter(
        (entry): entry is Record<string, unknown> =>
          typeof entry === "object" && entry !== null && !Array.isArray(entry),
      )
    : [];
  if (coupling.length > 0) {
    lines.push("| From | To | Confidence | Evidence |", "| --- | --- | --- | --- |");
    for (const edge of coupling) {
      let evidenceText = "";
      const evidence = edge.evidence;
      if (Array.isArray(evidence) && evidence.length > 0) {
        const first = evidence[0];
        if (typeof first === "object" && first !== null && !Array.isArray(first)) {
          const rec = first as Record<string, unknown>;
          evidenceText = `${rec.path ?? ""}:${rec.line ?? ""} imports ${rec.import ?? ""}`;
        }
      }
      lines.push(
        "| " +
          `${code(edge.from)} | ` +
          `${code(edge.to)} | ` +
          `${markdownText(edge.confidence)} | ` +
          `${markdownText(evidenceText)} |`,
      );
    }
  } else {
    lines.push("No cross-module coupling was reported by the selected artifact.");
  }

  lines.push("", "## Entry Points", "");
  const entryPoints = Array.isArray(artifact.entryPoints)
    ? artifact.entryPoints.filter(
        (entry): entry is Record<string, unknown> =>
          typeof entry === "object" && entry !== null && !Array.isArray(entry),
      )
    : [];
  if (entryPoints.length > 0) {
    lines.push("| Path | Module | Confidence |", "| --- | --- | --- |");
    for (const entry of entryPoints) {
      lines.push(
        "| " +
          `${code(entry.path)} | ` +
          `${code(entry.module)} | ` +
          `${markdownText(entry.confidence)} |`,
      );
    }
  } else {
    lines.push("No entry points were reported by the selected artifact.");
  }

  lines.push("", "## Languages", "");
  const languages = Array.isArray(artifact.languageDistribution)
    ? artifact.languageDistribution.filter(
        (entry): entry is Record<string, unknown> =>
          typeof entry === "object" && entry !== null && !Array.isArray(entry),
      )
    : [];
  if (languages.length > 0) {
    lines.push("| Language | Files |", "| --- | ---: |");
    for (const entry of languages) {
      lines.push(`| ${markdownText(entry.language)} | ${markdownText(entry.files)} |`);
    }
  } else {
    lines.push("No language distribution was reported by the selected artifact.");
  }

  lines.push("", "## Degraded Signals", "");
  const degraded = Array.isArray(artifact.degraded)
    ? artifact.degraded.filter(
        (entry): entry is Record<string, unknown> =>
          typeof entry === "object" && entry !== null && !Array.isArray(entry),
      )
    : [];
  if (degraded.length > 0) {
    for (const entry of degraded) {
      lines.push(`- ${code(entry.code)}: ${markdownText(entry.message)}`);
    }
  } else {
    lines.push("No degraded signals were reported by the selected artifact.");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

export function isDeftGenerated(path: string): boolean {
  if (!existsSync(path)) {
    return true;
  }
  try {
    return readFileSync(path, { encoding: "utf8" }).slice(0, 4096).includes(GENERATED_SENTINEL);
  } catch {
    return false;
  }
}

export function writeCodebaseMap(
  projectRoot: string,
  options: {
    outputPath: string;
    artifactPath?: string | null;
    generateWith?: string | null;
    force?: boolean;
  },
): string {
  const resolvedOutput = isAbsolute(options.outputPath)
    ? options.outputPath
    : join(projectRoot, options.outputPath);
  assertProjectionContained(projectRoot, resolvedOutput);
  if (!options.force && !isDeftGenerated(resolvedOutput)) {
    throw new Error(
      `refusing to overwrite non-generated MAP at ${resolvedOutput}; ` +
        `missing '${GENERATED_SENTINEL}' banner`,
    );
  }
  const selection = selectCodebaseMap(projectRoot, options.generateWith, {
    artifactPath: options.artifactPath,
  });
  const document = renderCodebaseMap(selection.artifact);
  // #2980 wave D: product write sink routes through containedWrite.
  const root = resolve(projectRoot);
  containedWrite({
    root,
    target: resolvedOutput,
    data: document,
    mode: "replace",
  });
  return resolvedOutput;
}

export interface CodebaseMapCliResult {
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

export function runCodebaseMapCli(argv: string[]): CodebaseMapCliResult {
  let projectRoot = ".";
  let output: string | undefined;
  let artifactPath: string | undefined;
  let generateWith: string | undefined;
  let stdout = false;
  let force = false;

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "--project-root") {
      const value = argv[i + 1];
      if (value === undefined) {
        return {
          exitCode: 2,
          stdout: "",
          stderr: "argument --project-root: expected one argument\n",
        };
      }
      projectRoot = value;
      i += 1;
    } else if (arg?.startsWith("--project-root=")) {
      projectRoot = arg.slice("--project-root=".length);
    } else if (arg === "--output") {
      const value = argv[i + 1];
      if (value === undefined) {
        return { exitCode: 2, stdout: "", stderr: "argument --output: expected one argument\n" };
      }
      output = value;
      i += 1;
    } else if (arg?.startsWith("--output=")) {
      output = arg.slice("--output=".length);
    } else if (arg === "--artifact-path") {
      const value = argv[i + 1];
      if (value === undefined) {
        return {
          exitCode: 2,
          stdout: "",
          stderr: "argument --artifact-path: expected one argument\n",
        };
      }
      artifactPath = value;
      i += 1;
    } else if (arg?.startsWith("--artifact-path=")) {
      artifactPath = arg.slice("--artifact-path=".length);
    } else if (arg === "--generate-with") {
      const value = argv[i + 1];
      if (value === undefined) {
        return {
          exitCode: 2,
          stdout: "",
          stderr: "argument --generate-with: expected one argument\n",
        };
      }
      generateWith = value;
      i += 1;
    } else if (arg?.startsWith("--generate-with=")) {
      generateWith = arg.slice("--generate-with=".length);
    } else if (arg === "--stdout") {
      stdout = true;
    } else if (arg === "--force") {
      force = true;
    }
  }

  const root = resolve(projectRoot);
  try {
    const outputPath = projectionOutputPath(root, output);
    const resolvedOutput = isAbsolute(outputPath) ? outputPath : join(root, outputPath);
    if (stdout) {
      const selection = selectCodebaseMap(root, generateWith, { artifactPath });
      const document = renderCodebaseMap(selection.artifact);
      return { exitCode: 0, stdout: document, stderr: "" };
    }

    writeCodebaseMap(root, { outputPath, artifactPath, generateWith, force });
    return { exitCode: 0, stdout: `Codebase MAP written to ${resolvedOutput}\n`, stderr: "" };
  } catch (err) {
    if (err instanceof CodeStructureConfigError || err instanceof Error) {
      return {
        exitCode: 2,
        stdout: "",
        stderr: sortedStringifyPretty(configErrorToDict(defaultCodeStructurePath(root), err)),
      };
    }
    throw err;
  }
}
