/** Generated-spec banner tokens (lockstep with Python ``_precutover.py``). */
export const GENERATED_SPEC_PURPOSE = "<!-- Purpose: rendered specification -->";

export const GENERATED_SPEC_SOURCE_SPEC =
  "<!-- Source of truth: vbrief/specification.vbrief.json -->";

export const GENERATED_SPEC_SOURCE_SPEC_XBRIEF =
  "<!-- Source of truth: xbrief/specification.xbrief.json -->";

export const GENERATED_SPEC_SOURCE_PD =
  "<!-- Source of truth: vbrief/PROJECT-DEFINITION.vbrief.json -->";

export const GENERATED_SPEC_SOURCE_PD_XBRIEF =
  "<!-- Source of truth: xbrief/PROJECT-DEFINITION.xbrief.json -->";

/** True when markdown carries a generated-spec source marker for either layout. */
export function contentHasGeneratedSpecSource(content: string): boolean {
  return (
    content.includes(GENERATED_SPEC_SOURCE_SPEC) ||
    content.includes(GENERATED_SPEC_SOURCE_SPEC_XBRIEF)
  );
}

/** True when markdown carries a generated greenfield PD source marker for either layout. */
export function contentHasGeneratedPdSource(content: string): boolean {
  return (
    content.includes(GENERATED_SPEC_SOURCE_PD) || content.includes(GENERATED_SPEC_SOURCE_PD_XBRIEF)
  );
}

export const EXPORT_SPEC_PD_BANNER =
  "<!-- AUTO-GENERATED by task project:export-spec -- DO NOT EDIT MANUALLY -->\n" +
  `${GENERATED_SPEC_PURPOSE}\n` +
  `${GENERATED_SPEC_SOURCE_PD}\n` +
  "<!-- Regenerate with: task project:export-spec -->\n";

/** Narratives excluded from stakeholder SPEC/PRD exports (#2013 Wave 0 §5). */
export const STAKEHOLDER_EXCLUDED_NARRATIVE_KEYS = new Set([
  "projectconfig",
  "tech stack",
  "techstack",
  "configuration",
]);

/** Product narrative keys used for migration-fidelity checks (#2005). */
export const PRODUCT_NARRATIVE_KEYS = [
  "ProblemStatement",
  "Goals",
  "UserStories",
  "Requirements",
  "SuccessMetrics",
  "FunctionalRequirements",
  "NonFunctionalRequirements",
  "AcceptanceCriteria",
  "Architecture",
  "EdgeCases",
] as const;

export const PROPOSED_DISCLAIMER_LINES = [
  "_Scopes in this section are ideas, not approved backlog. Promotion to pending is required before work starts._",
  "_Nothing here is in-flight or committed delivery scope._",
] as const;

export const PROPOSED_STATUS_FILTER = new Set(["draft", "proposed"]);
