import { basename, dirname, normalize, sep } from "node:path";

/** Generated-spec banner tokens (lockstep with Python ``_precutover.py``). */
export const GENERATED_SPEC_PURPOSE = "<!-- Purpose: rendered specification -->";

export const GENERATED_SPEC_SOURCE_SPEC =
  "<!-- Source of truth: vbrief/specification.vbrief.json -->";

export const GENERATED_SPEC_SOURCE_SPEC_XBRIEF =
  "<!-- Source of truth: xbrief/specification.xbrief.json -->";

export const GENERATED_SPEC_SOURCE_PD =
  "<!-- Source of truth: vbrief/PROJECT-DEFINITION.vbrief.json -->";

export const GENERATED_SPEC_SOURCE_PD_XBRIEF =
  "<!-- Source of truth: xbrief/PROJECT-DEFINITION.xbrief.json -->";

/** Stale vbrief generated-source banners aliased when the named file is gone (#4117). */
export const LEGACY_GENERATED_SPEC_SOURCE_MARKERS = [
  GENERATED_SPEC_SOURCE_SPEC,
  GENERATED_SPEC_SOURCE_PD,
] as const;

const GENERATED_SOURCE_MARKER = /^<!-- Source of truth: (.+?) -->\r?$/gm;
const PROJECT_DEFINITION_SOURCE = /(?:^|\/)PROJECT-DEFINITION\.(?:vbrief|xbrief)\.json$/i;

/** Return decoded non-PROJECT-DEFINITION source markers from generated markdown. */
export function generatedSpecSourcePaths(content: string): string[] {
  const sources: string[] = [];
  for (const match of content.matchAll(GENERATED_SOURCE_MARKER)) {
    let source: string | undefined;
    try {
      source = match[1] ? decodeURI(match[1]) : undefined;
    } catch {
      // A generated source path is URI-encoded by the banner writer. Reject
      // malformed escapes instead of guessing at a filesystem path.
    }
    if (source && !PROJECT_DEFINITION_SOURCE.test(source)) sources.push(source);
  }
  return sources;
}

/** True when markdown names the expected generated-spec source artifact. */
export function contentHasGeneratedSpecSource(
  content: string,
  expectedSourcePath: string,
): boolean {
  const expected = generatedSourcePath(expectedSourcePath);
  return generatedSpecSourcePaths(content).includes(expected);
}

/** True when markdown carries a generated greenfield PD source marker for either layout. */
export function contentHasGeneratedPdSource(content: string): boolean {
  return (
    content.includes(GENERATED_SPEC_SOURCE_PD) || content.includes(GENERATED_SPEC_SOURCE_PD_XBRIEF)
  );
}

/** Format a source path for a generated artifact banner. */
export function generatedSourcePath(sourcePath: string): string {
  const parent = basename(dirname(sourcePath));
  if (parent === "xbrief" || parent === "vbrief") {
    return `${parent}/${basename(sourcePath)}`;
  }
  return normalize(sourcePath).split(sep).join("/");
}

function generatedBannerValue(value: string): string {
  return value.replace(/\r\n?|\n/g, " ").replaceAll("-->", "--&gt;");
}

/** Build a canonical four-line generated-artifact banner from the actual source path. */
export function buildGeneratedArtifactBanner(
  generator: string,
  purpose: string,
  sourcePath: string,
): string {
  const safeGenerator = generatedBannerValue(generator);
  const safePurpose = generatedBannerValue(purpose);
  // Source paths must be reversible so an explicit --spec artifact can be
  // bound back to the resolved authority. URI encoding keeps CR/LF and an
  // embedded comment closer on one safe line without losing path identity.
  const safeSourcePath = encodeURI(generatedSourcePath(sourcePath));
  return (
    `<!-- AUTO-GENERATED by ${safeGenerator} -- DO NOT EDIT MANUALLY -->\n` +
    `<!-- Purpose: ${safePurpose} -->\n` +
    `<!-- Source of truth: ${safeSourcePath} -->\n` +
    `<!-- Regenerate with: ${safeGenerator} -->\n`
  );
}

/** Build the greenfield project export banner for the resolved PROJECT-DEFINITION path. */
export function buildExportSpecPdBanner(projectDefPath: string): string {
  return buildGeneratedArtifactBanner(
    "task project:export-spec",
    "rendered specification",
    projectDefPath,
  );
}

export const EXPORT_SPEC_PD_BANNER = buildExportSpecPdBanner(
  "xbrief/PROJECT-DEFINITION.xbrief.json",
);

/** Narratives excluded from stakeholder SPEC/PRD exports (#2013 Wave 0 §5). */
export const STAKEHOLDER_EXCLUDED_NARRATIVE_KEYS = new Set([
  "projectconfig",
  "tech stack",
  "techstack",
  "configuration",
]);

/** Product narrative keys used for migration-fidelity checks (#2005). */
export const PRODUCT_NARRATIVE_KEYS = [
  "ProblemStatement",
  "Goals",
  "UserStories",
  "Requirements",
  "SuccessMetrics",
  "FunctionalRequirements",
  "NonFunctionalRequirements",
  "AcceptanceCriteria",
  "Architecture",
  "EdgeCases",
] as const;

export const PROPOSED_DISCLAIMER_LINES = [
  "_Scopes in this section are ideas, not approved backlog. Promotion to pending is required before work starts._",
  "_Nothing here is in-flight or committed delivery scope._",
] as const;

export const PROPOSED_STATUS_FILTER = new Set(["draft", "proposed"]);
