import { execSync } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { REPO_ROOT, readRepoFile, repoFileExists } from "./helpers.js";

/** Port of tests/content/test_machine_generated_banner.py (#1838 #572) */

const REGISTERED_PURPOSES = [
  "rendered specification",
  "rendered PRD",
  "rendered roadmap",
  "deprecation redirect",
] as const;

const BANNER_PREFIX = "<!-- AUTO-GENERATED by ";

function runPythonScript(body: string): string {
  const dir = mkdtempSync(join(tmpdir(), "deft-banner-"));
  const scriptPath = join(dir, "run.py");
  writeFileSync(scriptPath, `import sys\nsys.path.insert(0, 'scripts')\n${body}`, "utf8");
  return execSync(`python3 "${scriptPath}"`, {
    cwd: REPO_ROOT,
    encoding: "utf8",
  }).trimEnd();
}

function assertCanonicalBanner(
  content: string,
  purpose: string,
  generator: string,
  source: string,
  regenerate: string,
): void {
  const bannerIdx = content.indexOf(BANNER_PREFIX);
  expect(bannerIdx).not.toBe(-1);
  const lines = content.slice(bannerIdx).split("\n");
  expect(lines.length).toBeGreaterThanOrEqual(4);
  expect(lines[0]?.startsWith(BANNER_PREFIX)).toBe(true);
  expect(lines[0]).toContain(generator);
  expect(lines[0]).toContain("DO NOT EDIT MANUALLY");
  expect(lines[1]).toBe(`<!-- Purpose: ${purpose} -->`);
  expect(REGISTERED_PURPOSES).toContain(purpose);
  expect(lines[2]).toBe(`<!-- Source of truth: ${source} -->`);
  expect(lines[3]).toBe(`<!-- Regenerate with: ${regenerate} -->`);
  for (let idx = 0; idx < 4; idx += 1) {
    expect(lines[idx]).not.toContain("{");
    expect(lines[idx]).not.toContain("}");
  }
}

describe("test_machine_generated_banner", () => {
  it.each([
    [
      "spec_render",
      "rendered specification",
      "task spec:render",
      "vbrief/specification.vbrief.json",
      "task spec:render",
      `
import json, tempfile
from pathlib import Path
tmpdir = Path(tempfile.mkdtemp())
spec = {"vBRIEFInfo": {"version": "0.6"}, "plan": {"title": "Banner Contract Test Project", "status": "approved", "narratives": {"Overview": "Fixture."}, "items": []}}
spec_path = tmpdir / "vbrief" / "specification.vbrief.json"
spec_path.parent.mkdir(parents=True, exist_ok=True)
spec_path.write_text(json.dumps(spec), encoding="utf-8")
import spec_render
out = tmpdir / "SPECIFICATION.md"
ok, msg = spec_render.render_spec(str(spec_path), str(out), include_scopes=False)
assert ok, msg
print(out.read_text(encoding="utf-8"), end="")
`,
    ],
    [
      "prd_render",
      "rendered PRD",
      "task prd:render",
      "vbrief/specification.vbrief.json",
      "task prd:render",
      `
import json, tempfile
from pathlib import Path
tmpdir = Path(tempfile.mkdtemp())
spec = {"vBRIEFInfo": {"version": "0.6"}, "plan": {"title": "Banner Contract Test Project", "status": "approved", "narratives": {"Overview": "Fixture."}, "items": []}}
spec_path = tmpdir / "vbrief" / "specification.vbrief.json"
spec_path.parent.mkdir(parents=True, exist_ok=True)
spec_path.write_text(json.dumps(spec), encoding="utf-8")
import prd_render
out = tmpdir / "PRD.md"
prd_render.render_prd(spec_path, out)
print(out.read_text(encoding="utf-8"), end="")
`,
    ],
    [
      "roadmap_render",
      "rendered roadmap",
      "task roadmap:render",
      "vbrief/pending/ (scope vBRIEFs)",
      "task roadmap:render",
      `
import json, tempfile
from pathlib import Path
tmpdir = Path(tempfile.mkdtemp())
pending = tmpdir / "vbrief" / "pending"
pending.mkdir(parents=True, exist_ok=True)
scope = {"vBRIEFInfo": {"version": "0.6"}, "plan": {"title": "Banner Contract Scope", "status": "pending", "items": [], "references": []}}
(pending / "2026-04-22-banner-contract-scope.vbrief.json").write_text(json.dumps(scope), encoding="utf-8")
import roadmap_render
out = tmpdir / "ROADMAP.md"
ok, msg = roadmap_render.render_roadmap(str(pending), str(out))
assert ok, msg
print(out.read_text(encoding="utf-8"), end="")
`,
    ],
    [
      "migrate_vbrief_deprecation_redirect",
      "deprecation redirect",
      "task migrate:vbrief",
      "n/a",
      "task migrate:vbrief",
      `
import migrate_vbrief
print(migrate_vbrief._deprecation_redirect("SPECIFICATION.md", "vbrief/PROJECT-DEFINITION.vbrief.json", "Fixture scope note."), end="")
`,
    ],
  ])("writer_emits_canonical_banner %s", (_writerId, purpose, generator, source, regenerate, pyBody) => {
    const content = runPythonScript(pyBody);
    assertCanonicalBanner(content, purpose, generator, source, regenerate);
  });

  it("registered_purposes_match_convention_doc", () => {
    const docPath = "conventions/machine-generated-banner.md";
    expect(repoFileExists(docPath)).toBe(true);
    const doc = readRepoFile(docPath);
    for (const purpose of REGISTERED_PURPOSES) {
      expect(doc).toContain(`\`${purpose}\``);
    }
  });

  it("migrator_auto_markers_include_canonical_banner_tokens", () => {
    runPythonScript(`
import migrate_vbrief
for name in ('_SPEC_AUTO_MARKERS', '_PROJECT_AUTO_MARKERS'):
    tup = getattr(migrate_vbrief, name)
    assert 'AUTO-GENERATED by' in tup
    assert '<!-- Purpose:' in tup
    assert 'Purpose:' not in tup
print('ok')
`);
  });

  it("setup_skill_detects_both_legacy_and_canonical_markers", () => {
    const text = readRepoFile("skills/deft-directive-setup/SKILL.md");
    expect(text).toContain("<!-- deft:deprecated-redirect -->");
    expect(text).toContain("Purpose: deprecation redirect");
  });
});
