import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { renderPrd } from "../../render/prd-render.js";
import { renderRoadmap } from "../../render/roadmap-render.js";
import { renderSpec } from "../../render/spec-render.js";
import { DEPRECATION_SENTINEL } from "../../vbrief-build/constants.js";
import { readRepoFile, repoFileExists } from "./helpers.js";

/** Port of tests/content/test_machine_generated_banner.py (#1838 #572) — TS render path (#1860). */

const REGISTERED_PURPOSES = [
  "rendered specification",
  "rendered PRD",
  "rendered roadmap",
  "deprecation redirect",
] as const;

const BANNER_PREFIX = "<!-- AUTO-GENERATED by ";

const SPEC_FIXTURE = {
  vBRIEFInfo: { version: "0.6" },
  plan: {
    title: "Banner Contract Test Project",
    status: "approved",
    narratives: { Overview: "Fixture." },
    items: [],
  },
};

function assertCanonicalBanner(
  content: string,
  purpose: string,
  generator: string,
  source: string,
  regenerate: string,
): void {
  const bannerIdx = content.indexOf(BANNER_PREFIX);
  expect(bannerIdx).not.toBe(-1);
  const lines = content.slice(bannerIdx).split("\n");
  expect(lines.length).toBeGreaterThanOrEqual(4);
  expect(lines[0]?.startsWith(BANNER_PREFIX)).toBe(true);
  expect(lines[0]).toContain(generator);
  expect(lines[0]).toContain("DO NOT EDIT MANUALLY");
  expect(lines[1]).toBe(`<!-- Purpose: ${purpose} -->`);
  expect(REGISTERED_PURPOSES).toContain(purpose);
  expect(lines[2]).toBe(`<!-- Source of truth: ${source} -->`);
  expect(lines[3]).toBe(`<!-- Regenerate with: ${regenerate} -->`);
  for (let idx = 0; idx < 4; idx += 1) {
    expect(lines[idx]).not.toContain("{");
    expect(lines[idx]).not.toContain("}");
  }
}

describe("test_machine_generated_banner", () => {
  it("writer_emits_canonical_banner spec_render", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-banner-"));
    const specPath = join(dir, "vbrief", "specification.vbrief.json");
    mkdirSync(join(dir, "vbrief"), { recursive: true });
    writeFileSync(specPath, JSON.stringify(SPEC_FIXTURE), "utf8");
    const out = join(dir, "SPECIFICATION.md");
    const [ok] = renderSpec(specPath, out, { includeScopes: false });
    expect(ok).toBe(true);
    assertCanonicalBanner(
      readFileSync(out, "utf8"),
      "rendered specification",
      "task spec:render",
      "vbrief/specification.vbrief.json",
      "task spec:render",
    );
  });

  it("writer_emits_canonical_banner prd_render", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-banner-"));
    const specPath = join(dir, "vbrief", "specification.vbrief.json");
    mkdirSync(join(dir, "vbrief"), { recursive: true });
    writeFileSync(specPath, JSON.stringify(SPEC_FIXTURE), "utf8");
    const out = join(dir, "PRD.md");
    renderPrd(specPath, out);
    assertCanonicalBanner(
      readFileSync(out, "utf8"),
      "rendered PRD",
      "task prd:render",
      "vbrief/specification.vbrief.json",
      "task prd:render",
    );
  });

  it("writer_emits_canonical_banner roadmap_render", () => {
    const dir = mkdtempSync(join(tmpdir(), "deft-banner-"));
    const pending = join(dir, "vbrief", "pending");
    mkdirSync(pending, { recursive: true });
    writeFileSync(
      join(pending, "2026-04-22-banner-contract-scope.vbrief.json"),
      JSON.stringify({
        vBRIEFInfo: { version: "0.6" },
        plan: { title: "Banner Contract Scope", status: "pending", items: [], references: [] },
      }),
      "utf8",
    );
    const out = join(dir, "ROADMAP.md");
    const [ok] = renderRoadmap(pending, out);
    expect(ok).toBe(true);
    assertCanonicalBanner(
      readFileSync(out, "utf8"),
      "rendered roadmap",
      "task roadmap:render",
      "xbrief|vbrief pending/ + proposed/ + active/ (forward); completed/ capped",
      "task roadmap:render",
    );
  });

  it("writer_emits_canonical_banner deprecation_redirect sentinel", () => {
    const content = `${DEPRECATION_SENTINEL}\n<!-- Purpose: deprecation redirect -->\n`;
    expect(content).toContain(DEPRECATION_SENTINEL);
    expect(content).toContain("Purpose: deprecation redirect");
  });

  it("registered_purposes_match_convention_doc", () => {
    const docPath = "conventions/machine-generated-banner.md";
    expect(repoFileExists(docPath)).toBe(true);
    const doc = readRepoFile(docPath);
    for (const purpose of REGISTERED_PURPOSES) {
      expect(doc).toContain(`\`${purpose}\``);
    }
  });

  it("setup_skill_detects_both_legacy_and_canonical_markers", () => {
    const text = readRepoFile("skills/deft-directive-setup/SKILL.md");
    expect(text).toContain("<!-- deft:deprecated-redirect -->");
    expect(text).toContain("Purpose: deprecation redirect");
  });
});
