import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { createScopeVbrief, referenceWithDefaultTrust, slugify } from "./build.js";
import { pythonJsonPretty } from "./json.js";
import {
  atomicWriteProjectDefinition,
  loadProjectDefinitionForMutation,
  projectDefinitionMutationLock,
} from "./project-definition-io.js";
import {
  buildScopeVbriefFromReconciled,
  folderForStatus,
  planStatusMatchesFolder,
} from "./routing.js";
import {
  deriveOverviewNarrative,
  extractTechStack,
  firstProseParagraph,
  parseRoadmapItems,
  resolveRepoUrl,
} from "./sources.js";
import {
  createSpeckitScopeVbrief,
  dependenciesForItem,
  edgeNodes,
  migrateSpeckitPlan,
  speckitIpIndex,
  speckitIpSlug,
} from "./speckit.js";
import type { JsonObject } from "./types.js";

export const SAMPLE_ROADMAP_MD = `# Roadmap

## Phase 1 -- Foundation

- **#100** -- Add widget support
- **#101** -- Fix login bug

## Phase 2 -- Features

- **#200** -- Dashboard redesign

## Completed

- ~~#50 -- Initial setup~~
`;

export const SAMPLE_SPEC_VBRIEF: JsonObject = {
  vBRIEFInfo: { version: "0.5", description: "Test spec" },
  plan: {
    title: "Test Specification",
    status: "approved",
    narratives: {
      Overview: "A test project for migration.",
      Architecture: "Simple architecture.",
    },
    items: [{ id: "t1.1", title: "Task one", status: "completed" }],
  },
};

export const SAMPLE_PROJECT_MD =
  "# Test Project\n\n" +
  "## Project Configuration\n\n" +
  "**Tech Stack**: Python\n\n" +
  "**Generated by**: deft-setup skill\n" +
  "**Date**: 2026-04-01\n";

export const SAMPLE_SPEC_MD =
  "# Test Specification\n\n" + "A test specification.\n\n" + "**Generated by**: spec_render.py\n";

export interface ParityScenarioContext {
  readonly fixtureRoot: string;
}

export interface ParityScenarioResult {
  readonly scenario: string;
  readonly ok: boolean;
  readonly payload: unknown;
}

function reconciledBase(overrides: JsonObject = {}): JsonObject {
  return {
    task_id: "#99",
    number: "99",
    title: "Widget feature",
    description: "Add a widget.",
    description_source: "SPECIFICATION.md",
    status: "pending",
    status_source: "default",
    folder: "pending",
    phase: "Phase 1",
    phase_description: "",
    tier: "",
    spec_phase: "",
    roadmap_summary: "",
    source_conflict: "",
    title_source: "",
    override_applied: false,
    synthetic_id: "",
    original_task_id: "",
    ...overrides,
  };
}

/** Execute a named parity scenario and return structured payload. */
export function runParityScenario(name: string, ctx: ParityScenarioContext): ParityScenarioResult {
  switch (name) {
    case "slugify-basic":
      return {
        scenario: name,
        ok: true,
        payload: {
          hello: slugify("Hello World"),
          special: slugify("Add widget (v2)!"),
          underscores: slugify("task_id_foo"),
        },
      };
    case "create-scope-vbrief":
      return {
        scenario: name,
        ok: true,
        payload: createScopeVbrief(
          { number: "99", title: "Test feature", phase: "Phase 1", tier: "Tier 1" },
          "https://github.com/owner/repo",
        ),
      };
    case "reference-trust-levels":
      return {
        scenario: name,
        ok: true,
        payload: {
          internal: referenceWithDefaultTrust({
            type: "x-vbrief/plan",
            uri: "specification.vbrief.json",
          }),
          external: referenceWithDefaultTrust({
            type: "x-vbrief/github-issue",
            uri: "https://github.com/o/r/issues/1",
            title: "Issue #1",
          }),
          preset: referenceWithDefaultTrust({
            type: "x-vbrief/github-issue",
            uri: "https://github.com/o/r/issues/1",
            title: "Issue #1",
            TrustLevel: "internal",
          }),
        },
      };
    case "parse-roadmap": {
      const roadmapPath = join(ctx.fixtureRoot, "ROADMAP.md");
      writeFileSync(roadmapPath, SAMPLE_ROADMAP_MD, "utf8");
      const parsed = parseRoadmapItems(roadmapPath);
      return { scenario: name, ok: true, payload: parsed };
    }
    case "resolve-repo-url":
      return {
        scenario: name,
        ok: true,
        payload: {
          fromRepository: resolveRepoUrl({
            vBRIEFInfo: { repository: "owner/repo" },
          }),
          fromRef: resolveRepoUrl({
            plan: {
              references: [{ uri: "https://github.com/acme/widget/issues/1" }],
            },
          }),
          empty: resolveRepoUrl(null),
        },
      };
    case "extract-tech-stack":
      return {
        scenario: name,
        ok: true,
        payload: extractTechStack(SAMPLE_PROJECT_MD),
      };
    case "first-prose-paragraph":
      return {
        scenario: name,
        ok: true,
        payload: firstProseParagraph(SAMPLE_SPEC_MD),
      };
    case "derive-overview":
      return {
        scenario: name,
        ok: true,
        payload: {
          fromSpec: deriveOverviewNarrative(SAMPLE_SPEC_VBRIEF, null, null, 0),
          fromSpecMd: deriveOverviewNarrative(null, SAMPLE_SPEC_MD, null, 0),
          placeholder: deriveOverviewNarrative(null, null, null, 3),
        },
      };
    case "routing-map":
      return {
        scenario: name,
        ok: true,
        payload: {
          running: folderForStatus("running"),
          matches: planStatusMatchesFolder("running", "active"),
        },
      };
    case "build-reconciled":
      return {
        scenario: name,
        ok: true,
        payload: buildScopeVbriefFromReconciled(
          reconciledBase({
            status: "completed",
            folder: "completed",
            source_section: "ROADMAP Completed section",
          }),
          "https://github.com/acme/widget",
          "2026-04-23T00:00:00Z",
        ),
      };
    case "speckit-edge-deps":
      return {
        scenario: name,
        ok: true,
        payload: {
          nodes: edgeNodes({ from: "a", to: "b" }),
          legacy: edgeNodes({ source: "x", target: "y" }),
          deps: dependenciesForItem("ip-2", [
            { type: "blocks", from: "ip-1", to: "ip-2" },
            { type: "blocks", source: "ip-0", target: "ip-2" },
          ]),
          slug: speckitIpSlug("IP-1: Widget phase", "ip-1"),
          index: speckitIpIndex({ id: "phase-ip-3", title: "IP 3: Build" }, 9),
        },
      };
    case "create-speckit-scope":
      return {
        scenario: name,
        ok: true,
        payload: createSpeckitScopeVbrief(
          {
            title: "IP-1: Foundation",
            narrative: {
              Description: "Build the foundation.",
              Acceptance: "Tests pass.",
              Traces: "REQ-1",
            },
          },
          { ipIndex: 1, dependencies: ["ip-0"], specRef: "../specification.vbrief.json" },
        ),
      };
    case "project-definition-roundtrip": {
      const vbriefDir = join(ctx.fixtureRoot, "vbrief");
      mkdirSync(vbriefDir, { recursive: true });
      const seed: JsonObject = {
        vBRIEFInfo: { version: "0.6" },
        plan: {
          title: "Parity project",
          status: "running",
          policy: { wipCap: 10 },
          items: [],
        },
      };
      const pdPath = join(vbriefDir, "PROJECT-DEFINITION.vbrief.json");
      writeFileSync(pdPath, pythonJsonPretty(seed), "utf8");
      let roundtrip: JsonObject = {};
      projectDefinitionMutationLock(ctx.fixtureRoot, () => {
        const [data, path] = loadProjectDefinitionForMutation(ctx.fixtureRoot);
        (data.plan as JsonObject).policy = { wipCap: 12 };
        atomicWriteProjectDefinition(path, data);
        roundtrip = JSON.parse(readFileSync(path, "utf8")) as JsonObject;
      });
      return { scenario: name, ok: true, payload: roundtrip };
    }
    case "migrate-speckit-plan": {
      const vbriefDir = join(ctx.fixtureRoot, "vbrief");
      mkdirSync(vbriefDir, { recursive: true });
      const planPath = join(vbriefDir, "plan.vbrief.json");
      const planFixture: JsonObject = {
        vBRIEFInfo: { version: "0.5", description: "Speckit plan" },
        plan: {
          title: "Session",
          items: [
            {
              id: "ip-1",
              title: "IP-1: Foundation",
              narrative: { Description: "Build it." },
            },
          ],
          edges: [],
        },
      };
      writeFileSync(planPath, pythonJsonPretty(planFixture), "utf8");
      const [ok, actions] = migrateSpeckitPlan(planPath, {
        pendingDir: join(vbriefDir, "pending"),
        today: "2026-04-23",
      });
      const pendingFiles = ["pending"];
      let pendingContent: JsonObject | null = null;
      try {
        const pendingPath = join(vbriefDir, "pending", "2026-04-23-ip001-foundation.vbrief.json");
        pendingContent = JSON.parse(readFileSync(pendingPath, "utf8")) as JsonObject;
      } catch {
        pendingContent = null;
      }
      const rewrittenPlan = JSON.parse(readFileSync(planPath, "utf8")) as JsonObject;
      return {
        scenario: name,
        ok,
        payload: { actions, pendingContent, rewrittenPlan, pendingFiles },
      };
    }
    case "extract-tech-stack-eos":
      // Regression coverage for the ``\Z`` (absolute end-of-string) anchor bug:
      // a ``## Tech Stack`` section that runs to end-of-string must be captured.
      return {
        scenario: name,
        ok: true,
        payload: {
          endOfString: extractTechStack("## Tech Stack\nRust + TypeScript"),
          trailingNewline: extractTechStack("## Tech Stack\nRust + TypeScript\n"),
          followedByHeading: extractTechStack("## Tech Stack\nRust\n## Next\nmore"),
          multiLine: extractTechStack("## Tech Stack\nRust\nVitest\n"),
        },
      };
    case "speckit-ip-index-edge":
      return {
        scenario: name,
        ok: true,
        payload: {
          longDigits: speckitIpIndex({ id: "12345678901234" }, 1),
          trailingWhitespace: speckitIpIndex({ id: "ip-7   " }, 1),
          trailingNewline: speckitIpIndex({ id: "ip-8\n" }, 1),
          titleFallback: speckitIpIndex({ id: "phase", title: "IP-3: Build" }, 9),
          noDigits: speckitIpIndex({ id: "phase-x", title: "no ip" }, 5),
        },
      };
    case "repo-url-trailing-slashes":
      return {
        scenario: name,
        ok: true,
        payload: {
          single: createScopeVbrief({ number: "5", title: "T" }, "https://github.com/o/r/"),
          multiple: createScopeVbrief({ number: "6", title: "U" }, "https://github.com/o/r///"),
          spaced: createScopeVbrief({ number: "7", title: "V" }, "  https://github.com/o/r//  "),
        },
      };
    default:
      return { scenario: name, ok: false, payload: { error: `unknown scenario: ${name}` } };
  }
}

export const PARITY_SCENARIO_NAMES = [
  "slugify-basic",
  "create-scope-vbrief",
  "reference-trust-levels",
  "parse-roadmap",
  "resolve-repo-url",
  "extract-tech-stack",
  "first-prose-paragraph",
  "derive-overview",
  "routing-map",
  "build-reconciled",
  "speckit-edge-deps",
  "create-speckit-scope",
  "project-definition-roundtrip",
  "migrate-speckit-plan",
  "extract-tech-stack-eos",
  "speckit-ip-index-edge",
  "repo-url-trailing-slashes",
] as const;

/** Render scenario output bytes for parity compare. */
export function renderScenarioOutput(result: ParityScenarioResult): string {
  return pythonJsonPretty(result);
}
