import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { runDeftTs } from "./deft-ts-runner.js";

const temps: string[] = [];
afterAll(() => {
  for (const t of temps) rmSync(t, { recursive: true, force: true });
});

function makePendingRoadmapFixture(): string {
  const root = mkdtempSync(join(tmpdir(), "deft-cli-roadmap-"));
  temps.push(root);
  const pending = join(root, "xbrief", "pending");
  mkdirSync(pending, { recursive: true });
  writeFileSync(
    join(pending, "2026-01-01-feature.xbrief.json"),
    JSON.stringify({
      xBRIEFInfo: { version: "0.8" },
      plan: {
        title: "Feature A",
        status: "pending",
        metadata: { "x-migrator": { Phase: "Phase 1", PhaseDescription: "Foundation" } },
        references: [{ uri: "https://github.com/deftai/directive/issues/42" }],
      },
    }),
    "utf8",
  );
  return root;
}

const VALID_SPEC_JSON = JSON.stringify({
  vBRIEFInfo: { version: "0.6" },
  plan: { title: "T", status: "approved", items: [] },
});

describe("deft-ts spec-validate", async () => {
  it("accepts a valid specification vBRIEF via direct path", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-val-"));
    temps.push(root);
    const specPath = join(root, "spec.json");
    writeFileSync(specPath, VALID_SPEC_JSON, "utf8");
    const result = await runDeftTs("spec-validate", [specPath]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("valid vBRIEF");
  });

  it("resolves xbrief/specification.xbrief.json via --project-root on migrated tree (#2132)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-val-xbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), VALID_SPEC_JSON, "utf8");
    const result = await runDeftTs("spec-validate", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("valid vBRIEF");
  });

  it("falls back to vbrief/specification.xbrief.json via --project-root on legacy tree (#2132)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-val-vbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), VALID_SPEC_JSON, "utf8");
    const result = await runDeftTs("spec-validate", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("valid vBRIEF");
  });
});

const APPROVED_SPEC_JSON = JSON.stringify({
  vBRIEFInfo: { version: "0.6" },
  plan: {
    title: "CLI Spec",
    status: "approved",
    narratives: { Overview: "Overview text" },
    items: [],
  },
});

describe("deft-ts spec-render", async () => {
  it("renders SPECIFICATION.md from an approved spec via direct path", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-render-"));
    temps.push(root);
    const vbrief = join(root, "xbrief");
    mkdirSync(vbrief, { recursive: true });
    const specPath = join(vbrief, "specification.xbrief.json");
    const outPath = join(root, "SPECIFICATION.md");
    writeFileSync(specPath, APPROVED_SPEC_JSON, "utf8");
    const result = await runDeftTs("spec-render", [specPath, outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("## Overview");
  });

  it("renders SPECIFICATION.md via --project-root on migrated xbrief tree (#2132)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-render-xbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), APPROVED_SPEC_JSON, "utf8");
    const result = await runDeftTs("spec-render", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(join(root, "SPECIFICATION.md"), "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("## Overview");
  });

  it("renders SPECIFICATION.md via --project-root on legacy vbrief tree (#2132)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-render-vbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), APPROVED_SPEC_JSON, "utf8");
    const result = await runDeftTs("spec-render", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(join(root, "SPECIFICATION.md"), "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("## Overview");
  });
});

const PRD_SPEC_JSON = JSON.stringify({
  xBRIEFInfo: { version: "0.8" },
  plan: {
    title: "PRD Title",
    status: "approved",
    narratives: { Overview: "Stakeholder overview" },
    items: [],
  },
});

function makeGreenfieldExportFixture(): string {
  const root = mkdtempSync(join(tmpdir(), "deft-cli-greenfield-export-"));
  temps.push(root);
  const xbrief = join(root, "xbrief");
  for (const folder of ["proposed", "pending", "active", "completed", "cancelled"]) {
    mkdirSync(join(xbrief, folder), { recursive: true });
  }
  writeFileSync(
    join(xbrief, "PROJECT-DEFINITION.xbrief.json"),
    JSON.stringify({
      xBRIEFInfo: { version: "0.8" },
      plan: {
        title: "Greenfield Product",
        status: "running",
        narratives: {
          Overview: "Greenfield overview",
          Architecture: "Greenfield architecture",
          ProjectConfig: "internal configuration",
          "tech stack": "private stack details",
        },
        items: [],
      },
    }),
    "utf8",
  );
  const writeScope = (folder: string, filename: string, title: string, status: string): void => {
    writeFileSync(
      join(xbrief, folder, filename),
      JSON.stringify({
        xBRIEFInfo: { version: "0.8" },
        plan: { title, status, narratives: { Overview: `${title} overview` }, items: [] },
      }),
      "utf8",
    );
  };
  writeScope("proposed", "2026-08-26-proposed.xbrief.json", "Proposed story", "proposed");
  writeScope("pending", "2026-08-26-pending.xbrief.json", "Pending story", "pending");
  writeScope("active", "2026-08-26-active.xbrief.json", "Active story", "running");
  writeScope("completed", "2026-08-26-completed.xbrief.json", "Completed story", "completed");
  return root;
}

describe("deft-ts greenfield setup export handoff", async () => {
  it("runs setup's exact export and PRD command shapes without manufacturing a spec artifact", async () => {
    const root = makeGreenfieldExportFixture();
    const stakeholderOut = join(root, "SPEC-stakeholder.md");
    const internalOut = join(root, "SPEC-internal.md");
    const internalOffOut = join(root, "SPEC-internal-off.md");
    const currentOut = join(root, "SPEC-internal-current.md");
    const allOut = join(root, "SPEC-internal-all.md");
    const prdOut = join(root, "PRD.md");

    expect((await runDeftTs("project:export-spec", [root, stakeholderOut])).exitCode).toBe(0);
    expect(
      (await runDeftTs("project:export-spec", [root, internalOut, "--audience=internal"])).exitCode,
    ).toBe(0);
    expect(
      (
        await runDeftTs("project:export-spec", [
          root,
          internalOffOut,
          "--audience=internal",
          "--no-scopes",
        ])
      ).exitCode,
    ).toBe(0);
    expect(
      (
        await runDeftTs("project:export-spec", [
          root,
          currentOut,
          "--audience=internal",
          "--include-scopes=current",
        ])
      ).exitCode,
    ).toBe(0);
    expect(
      (
        await runDeftTs("project:export-spec", [
          root,
          allOut,
          "--audience=internal",
          "--include-scopes=all",
        ])
      ).exitCode,
    ).toBe(0);
    expect(
      (await runDeftTs("prd-render", ["--project-root", root, "--output", prdOut])).exitCode,
    ).toBe(0);

    const stakeholder = readFileSync(stakeholderOut, "utf8");
    expect(stakeholder).toContain(
      "<!-- Source of truth: xbrief/PROJECT-DEFINITION.xbrief.json -->",
    );
    expect(stakeholder).not.toContain("## Scope outlook");

    const internal = readFileSync(internalOut, "utf8");
    expect(internal).toContain("## Scope outlook");
    expect(internal).toContain("Proposed story");
    expect(internal).not.toContain("Pending story");
    expect(internal).not.toContain("Active story");
    expect(internal).not.toContain("Completed story");
    expect(readFileSync(internalOffOut, "utf8")).not.toContain("## Scope outlook");

    const current = readFileSync(currentOut, "utf8");
    expect(current).toContain("Proposed story");
    expect(current).toContain("Pending story");
    expect(current).toContain("Active story");
    expect(current).not.toContain("Completed story");
    expect(readFileSync(allOut, "utf8")).toContain("Completed story");

    const prd = readFileSync(prdOut, "utf8");
    expect(prd).toContain("<!-- Source of truth: xbrief/PROJECT-DEFINITION.xbrief.json -->");
    expect(prd).toContain("Greenfield overview");
    expect(prd).not.toContain("ProjectConfig");
    expect(prd).not.toContain("tech stack");
    expect(prd).not.toContain("## Scope outlook");
    expect(prd).not.toContain("Proposed story");
    expect(existsSync(join(root, "xbrief", "specification.xbrief.json"))).toBe(false);
  });
});

describe("deft-ts prd-render", async () => {
  it("writes PRD.md from specification narratives via --spec path", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-prd-"));
    temps.push(root);
    const specPath = join(root, "spec.json");
    const outPath = join(root, "PRD.md");
    writeFileSync(specPath, PRD_SPEC_JSON, "utf8");
    const result = await runDeftTs("prd-render", ["--spec", specPath, "--output", outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Stakeholder overview");
    expect(content).toContain("<!-- Source of truth:");
    expect(content).toContain("spec.json -->");
  });

  it("rejects a null specification root without a TypeError", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-prd-null-root-"));
    temps.push(root);
    const specPath = join(root, "spec.json");
    const outPath = join(root, "PRD.md");
    writeFileSync(specPath, "null\n", "utf8");

    const result = await runDeftTs("prd-render", ["--spec", specPath, "--output", outPath]);

    expect([1, 2]).toContain(result.exitCode);
    expect(result.stderr).toContain(`${specPath} root must be a JSON object`);
    expect(result.stderr).not.toContain("TypeError");
    expect(existsSync(outPath)).toBe(false);
  });

  it("resolves spec via --project-root on migrated xbrief tree (#2132)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-prd-xbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), PRD_SPEC_JSON, "utf8");
    const outPath = join(root, "PRD.md");
    const result = await runDeftTs("prd-render", ["--project-root", root, "--output", outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Stakeholder overview");
    expect(content).toContain("<!-- Source of truth: xbrief/specification.xbrief.json -->");
  });

  it("resolves spec via --project-root on legacy vbrief tree (#2132)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-prd-vbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), PRD_SPEC_JSON, "utf8");
    const outPath = join(root, "PRD.md");
    const result = await runDeftTs("prd-render", ["--project-root", root, "--output", outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Stakeholder overview");
  });
});

describe("deft-ts project-render", async () => {
  it("creates PROJECT-DEFINITION.xbrief.json from lifecycle folders", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-proj-"));
    temps.push(root);
    const vbrief = join(root, "xbrief");
    for (const f of ["proposed", "pending", "active", "completed", "cancelled"]) {
      mkdirSync(join(vbrief, f), { recursive: true });
    }
    const result = await runDeftTs("project-render", [vbrief]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("PROJECT-DEFINITION.xbrief.json");
    expect(readFileSync(join(vbrief, "PROJECT-DEFINITION.xbrief.json"), "utf8")).toContain(
      "xBRIEFInfo",
    );
  });

  it("resolves xbrief/ layout via --project-root on migrated tree (#2139)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-proj-xbrief-"));
    temps.push(root);
    const xbrief = join(root, "xbrief");
    for (const f of ["proposed", "pending", "active", "completed", "cancelled"]) {
      mkdirSync(join(xbrief, f), { recursive: true });
    }
    writeFileSync(
      join(xbrief, "PROJECT-DEFINITION.xbrief.json"),
      JSON.stringify({
        xBRIEFInfo: { version: "0.8", created: "2026-07-01T00:00:00Z" },
        plan: { title: "T", status: "running", narratives: {}, items: [], metadata: {} },
      }),
      "utf8",
    );
    const result = await runDeftTs("project-render", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("PROJECT-DEFINITION.xbrief.json");
  });

  it("falls back to vbrief/ via --project-root on legacy tree (#2139)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-proj-vbrief-"));
    temps.push(root);
    const vbrief = join(root, "xbrief");
    for (const f of ["proposed", "pending", "active", "completed", "cancelled"]) {
      mkdirSync(join(vbrief, f), { recursive: true });
    }
    const result = await runDeftTs("project-render", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("PROJECT-DEFINITION.xbrief.json");
  });
});

describe("deft-ts roadmap-render", async () => {
  it("renders ROADMAP.md for pending vBRIEFs", async () => {
    const root = makePendingRoadmapFixture();
    const outPath = join(root, "ROADMAP.md");
    const pending = join(root, "xbrief", "pending");
    const result = await runDeftTs("roadmap-render", [pending, outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("# Roadmap");
    expect(content).toContain("Phase 1");
    expect(content).toContain("#42");
  });

  it("reports drift with --check when file is stale", async () => {
    const root = makePendingRoadmapFixture();
    const outPath = join(root, "ROADMAP.md");
    const pending = join(root, "xbrief", "pending");
    writeFileSync(outPath, "stale roadmap\n", "utf8");
    const result = await runDeftTs("roadmap-render", ["--check", pending, outPath]);
    expect(result.exitCode).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/drift|out of date/i);
  });

  it("accepts empty pending directory", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-roadmap-empty-"));
    temps.push(root);
    const pending = join(root, "xbrief", "pending");
    mkdirSync(pending, { recursive: true });
    const outPath = join(root, "ROADMAP.md");
    const result = await runDeftTs("roadmap-render", [pending, outPath]);
    expect(result.exitCode).toBe(0);
    expect(readFileSync(outPath, "utf8")).toContain("No pending work items");
  });

  it("resolves xbrief/pending/ via --project-root on migrated tree (#2139)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-roadmap-xbrief-"));
    temps.push(root);
    const pending = join(root, "xbrief", "pending");
    mkdirSync(pending, { recursive: true });
    writeFileSync(
      join(pending, "2026-01-01-feature.xbrief.json"),
      JSON.stringify({
        vBRIEFInfo: { version: "0.8" },
        plan: { title: "Feature X", status: "pending", references: [{ id: "#9" }] },
      }),
      "utf8",
    );
    const outPath = join(root, "ROADMAP.md");
    const result = await runDeftTs("roadmap-render", ["--project-root", root, outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("Feature X");
  });

  it("--check mode resolves xbrief/pending/ via --project-root (#2139)", async () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-roadmap-check-xbrief-"));
    temps.push(root);
    const pending = join(root, "xbrief", "pending");
    mkdirSync(pending, { recursive: true });
    writeFileSync(
      join(pending, "2026-01-01-feature.xbrief.json"),
      JSON.stringify({
        vBRIEFInfo: { version: "0.8" },
        plan: { title: "Feature Y", status: "pending", references: [{ id: "#10" }] },
      }),
      "utf8",
    );
    const outPath = join(root, "ROADMAP.md");
    await runDeftTs("roadmap-render", ["--project-root", root, outPath]);
    const result = await runDeftTs("roadmap-render", ["--project-root", root, outPath, "--check"]);
    expect(result.exitCode).toBe(0);
  });
});

describe("deft-ts framework-commands", async () => {
  it("prints help when invoked without a verb", async () => {
    const result = await runDeftTs("framework-commands", []);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Available framework verbs");
    expect(result.stdout).toContain("doctor");
  });

  it("returns exit 2 for unknown framework command", async () => {
    const result = await runDeftTs("framework-commands", ["__missing__"]);
    expect(result.exitCode).toBe(2);
  });

  it("registers triage:queue in help surface", async () => {
    const result = await runDeftTs("framework-commands", ["--help"]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("triage:queue");
  });
});

describe("deft-ts doctor", async () => {
  it("runs doctor --session on the framework root", async () => {
    const result = await runDeftTs("doctor", ["--session"]);
    expect([0, 1]).toContain(result.exitCode);
    expect(result.stdout + result.stderr).toMatch(/doctor|Deft/i);
  });
});
