import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterAll, describe, expect, it } from "vitest";
import { runDeftTs } from "./deft-ts-runner.js";

const temps: string[] = [];
afterAll(() => {
  for (const t of temps) rmSync(t, { recursive: true, force: true });
});

function makePendingRoadmapFixture(): string {
  const root = mkdtempSync(join(tmpdir(), "deft-cli-roadmap-"));
  temps.push(root);
  const pending = join(root, "vbrief", "pending");
  mkdirSync(pending, { recursive: true });
  writeFileSync(
    join(pending, "2026-01-01-feature.vbrief.json"),
    JSON.stringify({
      vBRIEFInfo: { version: "0.6" },
      plan: {
        title: "Feature A",
        status: "pending",
        metadata: { "x-migrator": { Phase: "Phase 1", PhaseDescription: "Foundation" } },
        references: [{ uri: "https://github.com/deftai/directive/issues/42" }],
      },
    }),
    "utf8",
  );
  return root;
}

const VALID_SPEC_JSON = JSON.stringify({
  vBRIEFInfo: { version: "0.6" },
  plan: { title: "T", status: "approved", items: [] },
});

describe("deft-ts spec-validate", () => {
  it("accepts a valid specification vBRIEF via direct path", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-val-"));
    temps.push(root);
    const specPath = join(root, "spec.json");
    writeFileSync(specPath, VALID_SPEC_JSON, "utf8");
    const result = runDeftTs("spec-validate", [specPath]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("valid vBRIEF");
  });

  it("resolves xbrief/specification.xbrief.json via --project-root on migrated tree (#2132)", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-val-xbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), VALID_SPEC_JSON, "utf8");
    const result = runDeftTs("spec-validate", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("valid vBRIEF");
  });

  it("falls back to vbrief/specification.vbrief.json via --project-root on legacy tree (#2132)", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-val-vbrief-"));
    temps.push(root);
    mkdirSync(join(root, "vbrief"), { recursive: true });
    writeFileSync(join(root, "vbrief", "specification.vbrief.json"), VALID_SPEC_JSON, "utf8");
    const result = runDeftTs("spec-validate", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("valid vBRIEF");
  });
});

const APPROVED_SPEC_JSON = JSON.stringify({
  vBRIEFInfo: { version: "0.6" },
  plan: {
    title: "CLI Spec",
    status: "approved",
    narratives: { Overview: "Overview text" },
    items: [],
  },
});

describe("deft-ts spec-render", () => {
  it("renders SPECIFICATION.md from an approved spec via direct path", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-render-"));
    temps.push(root);
    const vbrief = join(root, "vbrief");
    mkdirSync(vbrief, { recursive: true });
    const specPath = join(vbrief, "specification.vbrief.json");
    const outPath = join(root, "SPECIFICATION.md");
    writeFileSync(specPath, APPROVED_SPEC_JSON, "utf8");
    const result = runDeftTs("spec-render", [specPath, outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("## Overview");
  });

  it("renders SPECIFICATION.md via --project-root on migrated xbrief tree (#2132)", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-render-xbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), APPROVED_SPEC_JSON, "utf8");
    const result = runDeftTs("spec-render", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(join(root, "SPECIFICATION.md"), "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("## Overview");
  });

  it("renders SPECIFICATION.md via --project-root on legacy vbrief tree (#2132)", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-spec-render-vbrief-"));
    temps.push(root);
    mkdirSync(join(root, "vbrief"), { recursive: true });
    writeFileSync(join(root, "vbrief", "specification.vbrief.json"), APPROVED_SPEC_JSON, "utf8");
    const result = runDeftTs("spec-render", ["--project-root", root]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(join(root, "SPECIFICATION.md"), "utf8");
    expect(content).toContain("AUTO-GENERATED by task spec:render");
    expect(content).toContain("## Overview");
  });
});

const PRD_SPEC_JSON = JSON.stringify({
  vBRIEFInfo: { version: "0.6" },
  plan: {
    title: "PRD Title",
    status: "approved",
    narratives: { Overview: "Stakeholder overview" },
    items: [],
  },
});

describe("deft-ts prd-render", () => {
  it("writes PRD.md from specification narratives via --spec path", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-prd-"));
    temps.push(root);
    const specPath = join(root, "spec.json");
    const outPath = join(root, "PRD.md");
    writeFileSync(specPath, PRD_SPEC_JSON, "utf8");
    const result = runDeftTs("prd-render", ["--spec", specPath, "--output", outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Stakeholder overview");
  });

  it("resolves spec via --project-root on migrated xbrief tree (#2132)", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-prd-xbrief-"));
    temps.push(root);
    mkdirSync(join(root, "xbrief"), { recursive: true });
    writeFileSync(join(root, "xbrief", "specification.xbrief.json"), PRD_SPEC_JSON, "utf8");
    const outPath = join(root, "PRD.md");
    const result = runDeftTs("prd-render", ["--project-root", root, "--output", outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Stakeholder overview");
  });

  it("resolves spec via --project-root on legacy vbrief tree (#2132)", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-prd-vbrief-"));
    temps.push(root);
    mkdirSync(join(root, "vbrief"), { recursive: true });
    writeFileSync(join(root, "vbrief", "specification.vbrief.json"), PRD_SPEC_JSON, "utf8");
    const outPath = join(root, "PRD.md");
    const result = runDeftTs("prd-render", ["--project-root", root, "--output", outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("AUTO-GENERATED by task prd:render");
    expect(content).toContain("Stakeholder overview");
  });
});

describe("deft-ts project-render", () => {
  it("creates PROJECT-DEFINITION.vbrief.json from lifecycle folders", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-proj-"));
    temps.push(root);
    const vbrief = join(root, "vbrief");
    for (const f of ["proposed", "pending", "active", "completed", "cancelled"]) {
      mkdirSync(join(vbrief, f), { recursive: true });
    }
    const result = runDeftTs("project-render", [vbrief]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("PROJECT-DEFINITION.vbrief.json");
    expect(readFileSync(join(vbrief, "PROJECT-DEFINITION.vbrief.json"), "utf8")).toContain(
      "vBRIEFInfo",
    );
  });
});

describe("deft-ts roadmap-render", () => {
  it("renders ROADMAP.md for pending vBRIEFs", () => {
    const root = makePendingRoadmapFixture();
    const outPath = join(root, "ROADMAP.md");
    const pending = join(root, "vbrief", "pending");
    const result = runDeftTs("roadmap-render", [pending, outPath]);
    expect(result.exitCode).toBe(0);
    const content = readFileSync(outPath, "utf8");
    expect(content).toContain("# Roadmap");
    expect(content).toContain("Phase 1");
    expect(content).toContain("#42");
  });

  it("reports drift with --check when file is stale", () => {
    const root = makePendingRoadmapFixture();
    const outPath = join(root, "ROADMAP.md");
    const pending = join(root, "vbrief", "pending");
    writeFileSync(outPath, "stale roadmap\n", "utf8");
    const result = runDeftTs("roadmap-render", ["--check", pending, outPath]);
    expect(result.exitCode).toBe(1);
    expect(result.stdout + result.stderr).toMatch(/drift|out of date/i);
  });

  it("accepts empty pending directory", () => {
    const root = mkdtempSync(join(tmpdir(), "deft-cli-roadmap-empty-"));
    temps.push(root);
    const pending = join(root, "vbrief", "pending");
    mkdirSync(pending, { recursive: true });
    const outPath = join(root, "ROADMAP.md");
    const result = runDeftTs("roadmap-render", [pending, outPath]);
    expect(result.exitCode).toBe(0);
    expect(readFileSync(outPath, "utf8")).toContain("No pending work items");
  });
});

describe("deft-ts framework-commands", () => {
  it("prints help when invoked without a verb", () => {
    const result = runDeftTs("framework-commands", []);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("Available framework verbs");
    expect(result.stdout).toContain("doctor");
  });

  it("returns exit 2 for unknown framework command", () => {
    const result = runDeftTs("framework-commands", ["__missing__"]);
    expect(result.exitCode).toBe(2);
  });

  it("registers triage:queue in help surface", () => {
    const result = runDeftTs("framework-commands", ["--help"]);
    expect(result.exitCode).toBe(0);
    expect(result.stdout).toContain("triage:queue");
  });
});

describe("deft-ts doctor", () => {
  it("runs doctor --session on the framework root", () => {
    const result = runDeftTs("doctor", ["--session"]);
    expect([0, 1]).toContain(result.exitCode);
    expect(result.stdout + result.stderr).toMatch(/doctor|Deft/i);
  });
});
