#!/usr/bin/env python3
"""
migrate_vbrief.py -- Migrate a Deft project to the vBRIEF-centric document model.

Converts existing SPECIFICATION.md + specification.vbrief.json + PROJECT.md +
ROADMAP.md into the new lifecycle folder structure defined by RFC #309.

Usage:
    uv run python scripts/migrate_vbrief.py [project_root]

    project_root -- path to the project root (default: current working directory)

Exit codes:
    0 -- migration completed successfully
    1 -- migration failed (errors printed to stderr)

Story: #312 (Phase 2 vBRIEF Architecture Cutover)
"""

from __future__ import annotations

import json
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

# Lifecycle folders per RFC #309 D13
LIFECYCLE_FOLDERS = ("proposed", "pending", "active", "completed", "cancelled")

# Deprecation redirect sentinel per Story S (#334)
DEPRECATION_SENTINEL = "<!-- deft:deprecated-redirect -->"

# Known auto-generated markers for detecting user customization
_SPEC_AUTO_MARKERS = (
    "Generated by",
    "deft-setup skill",
    "spec_render.py",
)
_PROJECT_AUTO_MARKERS = (
    "Generated by",
    "deft-setup skill",
)

# Date for migration-created vBRIEF filenames (D7: creation date)
_TODAY = datetime.now(UTC).strftime("%Y-%m-%d")


def _is_user_customized(content: str, auto_markers: tuple[str, ...]) -> bool:
    """Check if file content has been customized beyond auto-generated content.

    Returns True if the content does NOT contain any of the known auto-generation
    markers, suggesting the user has substantially rewritten the file.
    """
    return not any(marker in content for marker in auto_markers)


def _slugify(text: str) -> str:
    """Convert a title to a filename-safe slug."""
    slug = text.lower().strip()
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug[:60].strip("-")


def _parse_roadmap_items(roadmap_path: Path) -> list[dict]:
    """Parse ROADMAP.md and extract items as structured data.

    Returns a list of dicts with keys: number, title, phase, description.
    """
    if not roadmap_path.exists():
        return []

    content = roadmap_path.read_text(encoding="utf-8")
    items: list[dict] = []
    current_phase = ""

    for line in content.splitlines():
        # Detect phase headings
        phase_match = re.match(r"^##\s+(.+)", line)
        if phase_match:
            current_phase = phase_match.group(1).strip()
            # Skip Completed section
            if "completed" in current_phase.lower():
                current_phase = ""
            continue

        if not current_phase:
            continue

        # Match roadmap items: - **#NNN** -- Title
        item_match = re.match(r"^-\s+\*\*#(\d+)\*\*\s+--\s+(.+)", line)
        if item_match:
            number = item_match.group(1)
            title = item_match.group(2).strip()
            items.append({
                "number": number,
                "title": title,
                "phase": current_phase,
            })

    return items


def _build_project_definition(
    spec_vbrief: dict | None,
    project_content: str | None,
    scope_items: list[dict],
) -> dict:
    """Build PROJECT-DEFINITION.vbrief.json from existing sources.

    Per RFC #309 D3:
    - narratives holds project identity (overview, tech stack, architecture, risks, config)
    - items acts as a scope registry referencing individual vBRIEF files
    """
    narratives: dict[str, str] = {}

    # Extract from specification.vbrief.json
    if spec_vbrief:
        plan = spec_vbrief.get("plan", {})
        if isinstance(plan, dict):
            spec_narratives = plan.get("narratives", {})
            if isinstance(spec_narratives, dict):
                for key, value in spec_narratives.items():
                    if isinstance(value, str):
                        narratives[key] = value

    # Extract from PROJECT.md
    if project_content:
        narratives["ProjectConfig"] = project_content

    items: list[dict] = []
    for scope in scope_items:
        item: dict = {
            "id": f"scope-{scope.get('number', 'unknown')}",
            "title": scope.get("title", "Untitled"),
            "status": "pending",
        }
        # Origin provenance per D11
        number = scope.get("number")
        if number:
            item["references"] = [{
                "type": "github-issue",
                "url": f"https://github.com/deftai/directive/issues/{number}",
                "id": f"#{number}",
            }]
        items.append(item)

    return {
        "vBRIEFInfo": {
            "version": "0.5",
            "description": "Project definition -- synthesized gestalt of the project.",
        },
        "plan": {
            "title": "PROJECT-DEFINITION",
            "status": "running",
            "narratives": narratives,
            "items": items,
        },
    }


def _create_scope_vbrief(item: dict) -> dict:
    """Create an individual scope vBRIEF from a roadmap item.

    Per RFC #309 D7: filename uses creation date + descriptive slug.
    Per D11: origin provenance via references.
    """
    number = item.get("number", "")
    title = item.get("title", "Untitled")
    phase = item.get("phase", "")

    vbrief: dict = {
        "vBRIEFInfo": {
            "version": "0.5",
            "description": f"Scope vBRIEF for #{number}: {title}",
        },
        "plan": {
            "title": title,
            "status": "pending",
            "narratives": {
                "Description": title,
                "Phase": phase,
            },
            "items": [],
        },
    }

    # Origin provenance per D11
    if number:
        vbrief["plan"]["references"] = [{
            "type": "github-issue",
            "url": f"https://github.com/deftai/directive/issues/{number}",
            "id": f"#{number}",
        }]

    return vbrief


def _deprecation_redirect(
    original_name: str,
    pointer_target: str,
    scope_note: str,
) -> str:
    """Generate deprecation redirect content for a replaced file."""
    return (
        f"{DEPRECATION_SENTINEL}\n"
        f"# {original_name} -- DEPRECATED\n"
        f"\n"
        f"This file has been replaced by the vBRIEF-centric document model.\n"
        f"\n"
        f"**See instead:**\n"
        f"- `{pointer_target}` -- project definition and scope registry\n"
        f"- `vbrief/pending/` -- individual scope vBRIEFs (backlog)\n"
        f"- `vbrief/active/` -- in-progress scope vBRIEFs\n"
        f"\n"
        f"{scope_note}\n"
        f"\n"
        f"Migrated on {_TODAY} by `task migrate:vbrief` (RFC #309, Story #312).\n"
    )


def migrate(project_root: Path) -> tuple[bool, list[str]]:
    """Run the full migration on the given project root.

    Returns:
        (True, actions) on success -- actions is a list of human-readable lines.
        (False, errors) on failure.
    """
    actions: list[str] = []
    warnings: list[str] = []
    vbrief_dir = project_root / "vbrief"

    # ---- Step 1: Create lifecycle folders ----
    for folder_name in LIFECYCLE_FOLDERS:
        folder = vbrief_dir / folder_name
        if folder.exists():
            actions.append(f"SKIP  lifecycle folder already exists: vbrief/{folder_name}/")
        else:
            folder.mkdir(parents=True, exist_ok=True)
            actions.append(f"CREATE lifecycle folder: vbrief/{folder_name}/")

    # ---- Step 2: Read existing sources ----
    spec_vbrief_path = vbrief_dir / "specification.vbrief.json"
    spec_vbrief: dict | None = None
    if spec_vbrief_path.exists():
        try:
            spec_vbrief = json.loads(spec_vbrief_path.read_text(encoding="utf-8"))
            actions.append("READ  vbrief/specification.vbrief.json")
        except json.JSONDecodeError as exc:
            return False, [f"ERROR: invalid JSON in specification.vbrief.json: {exc}"]
    else:
        actions.append("SKIP  vbrief/specification.vbrief.json not found")

    spec_md_path = project_root / "SPECIFICATION.md"
    spec_md_content: str | None = None
    if spec_md_path.exists():
        spec_md_content = spec_md_path.read_text(encoding="utf-8")
        actions.append("READ  SPECIFICATION.md")

    project_md_path = project_root / "PROJECT.md"
    project_content: str | None = None
    if project_md_path.exists():
        project_content = project_md_path.read_text(encoding="utf-8")
        actions.append("READ  PROJECT.md")

    roadmap_path = project_root / "ROADMAP.md"
    roadmap_items = _parse_roadmap_items(roadmap_path)
    if roadmap_items:
        actions.append(f"READ  ROADMAP.md ({len(roadmap_items)} items parsed)")
    else:
        actions.append("SKIP  ROADMAP.md not found or no items parsed")

    # ---- Step 3: Generate PROJECT-DEFINITION.vbrief.json ----
    proj_def_path = vbrief_dir / "PROJECT-DEFINITION.vbrief.json"
    if proj_def_path.exists():
        actions.append("SKIP  PROJECT-DEFINITION.vbrief.json already exists (idempotent)")
    else:
        proj_def = _build_project_definition(spec_vbrief, project_content, roadmap_items)
        proj_def_path.write_text(
            json.dumps(proj_def, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        actions.append("CREATE vbrief/PROJECT-DEFINITION.vbrief.json")

    # ---- Step 4: Convert roadmap items to pending/ vBRIEFs ----
    for item in roadmap_items:
        number = item.get("number", "unknown")
        slug = _slugify(item.get("title", "untitled"))
        filename = f"{_TODAY}-{slug}.vbrief.json"
        target_path = vbrief_dir / "pending" / filename

        if target_path.exists():
            actions.append(f"SKIP  pending/{filename} already exists (idempotent)")
            continue

        # Check if any existing file references this issue number
        existing = _find_existing_scope_vbrief(vbrief_dir, number)
        if existing:
            actions.append(
                f"SKIP  #{number} already has scope vBRIEF: {existing.relative_to(vbrief_dir)}"
            )
            continue

        scope_vbrief = _create_scope_vbrief(item)
        target_path.write_text(
            json.dumps(scope_vbrief, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        actions.append(f"CREATE pending/{filename} (#{number})")

    # ---- Step 5: Deprecation redirects ----
    if spec_md_path.exists():
        if spec_md_content and DEPRECATION_SENTINEL in spec_md_content:
            actions.append("SKIP  SPECIFICATION.md already has deprecation redirect")
        else:
            # Check for user customization
            if spec_md_content and _is_user_customized(spec_md_content, _SPEC_AUTO_MARKERS):
                warnings.append(
                    "WARNING: SPECIFICATION.md appears user-customized. "
                    "Original content preserved in PROJECT-DEFINITION.vbrief.json narratives."
                )
                # Fold custom content into project definition
                _fold_custom_content(proj_def_path, "SpecificationContent", spec_md_content or "")

            redirect = _deprecation_redirect(
                "SPECIFICATION.md",
                "vbrief/PROJECT-DEFINITION.vbrief.json",
                "For scope details, see individual vBRIEF files in the lifecycle folders.",
            )
            spec_md_path.write_text(redirect, encoding="utf-8")
            actions.append("REPLACE SPECIFICATION.md with deprecation redirect")

    if project_md_path.exists():
        if project_content and DEPRECATION_SENTINEL in project_content:
            actions.append("SKIP  PROJECT.md already has deprecation redirect")
        else:
            # Check for user customization
            if project_content and _is_user_customized(project_content, _PROJECT_AUTO_MARKERS):
                warnings.append(
                    "WARNING: PROJECT.md appears user-customized. "
                    "Original content preserved in PROJECT-DEFINITION.vbrief.json narratives."
                )
                _fold_custom_content(proj_def_path, "ProjectConfig", project_content or "")

            redirect = _deprecation_redirect(
                "PROJECT.md",
                "vbrief/PROJECT-DEFINITION.vbrief.json",
                "For project configuration, see the narratives section.",
            )
            project_md_path.write_text(redirect, encoding="utf-8")
            actions.append("REPLACE PROJECT.md with deprecation redirect")

    # ---- Report ----
    for w in warnings:
        actions.append(w)

    return True, actions


def _find_existing_scope_vbrief(vbrief_dir: Path, issue_number: str) -> Path | None:
    """Check if any existing vBRIEF in lifecycle folders references the issue."""
    for folder_name in LIFECYCLE_FOLDERS:
        folder = vbrief_dir / folder_name
        if not folder.exists():
            continue
        for fpath in folder.glob("*.vbrief.json"):
            try:
                data = json.loads(fpath.read_text(encoding="utf-8"))
                refs = data.get("plan", {}).get("references", [])
                for ref in refs:
                    if ref.get("id") == f"#{issue_number}":
                        return fpath
            except (json.JSONDecodeError, AttributeError):
                continue
    return None


def _fold_custom_content(proj_def_path: Path, key: str, content: str) -> None:
    """Fold custom content into PROJECT-DEFINITION.vbrief.json narratives."""
    if not proj_def_path.exists():
        return
    try:
        data = json.loads(proj_def_path.read_text(encoding="utf-8"))
        narratives = data.get("plan", {}).get("narratives", {})
        narratives[key] = content
        proj_def_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
    except (json.JSONDecodeError, AttributeError):
        pass


def main() -> int:
    """Entry point for the migration script."""
    project_root = Path(sys.argv[1]).resolve() if len(sys.argv) >= 2 else Path.cwd()

    if not project_root.is_dir():
        print(f"ERROR: {project_root} is not a directory", file=sys.stderr)
        return 1

    print(f"Migrating project at: {project_root}")
    print("=" * 60)

    ok, messages = migrate(project_root)

    for msg in messages:
        print(f"  {msg}")

    print("=" * 60)
    if ok:
        print("Migration completed successfully.")
        return 0
    print("Migration FAILED.", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
