#!/usr/bin/env python3
"""pack_render.py -- regenerate meta/lessons.md from the canonical pack source.

Renders ``packs/lessons/lessons-pack-0.1.json`` (the source of truth per
ADR-001) into ``meta/lessons.md`` as a derivative projection. The renderer
OWNS the document chrome: a canonical machine-generated banner (per
``conventions/machine-generated-banner.md``, plus an ADR-001 Layer-A slice
deflection pointer) followed by the ``# Lessons Learned`` title and each
lesson entry rendered as ``## {title}\\n\\n{body}``.

The same render function backs both the write path (``task packs:render``)
and the drift gate (``--check`` / ``task verify:pack-drift``), so the
committed projection and a freshly re-rendered buffer match by construction.

Usage::

    uv run python scripts/pack_render.py            # write meta/lessons.md
    uv run python scripts/pack_render.py --check     # drift gate (no write)
    uv run python scripts/pack_render.py --source <json> --output <md>

Exit codes:
    0 -- rendered (write mode) OR no drift (check mode)
    1 -- drift detected (check mode) OR source missing
    2 -- usage error
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Repo root resolved from this file's location (scripts/ -> repo root) so the
# default source / output paths are CWD-independent.
REPO_ROOT = Path(__file__).resolve().parent.parent

DEFAULT_SOURCE = REPO_ROOT / "packs" / "lessons" / "lessons-pack-0.1.json"
DEFAULT_OUTPUT = REPO_ROOT / "meta" / "lessons.md"

# Canonical 4-line machine-generated banner (conventions/machine-generated-banner.md)
# plus a 5th ADR-001 Layer-A deflection line pointing humans/agents at the
# slice surface instead of loading the whole projection.
BANNER = (
    "<!-- AUTO-GENERATED by task packs:render -- DO NOT EDIT MANUALLY -->\n"
    "<!-- Purpose: rendered lessons -->\n"
    "<!-- Source of truth: packs/lessons/lessons-pack-0.1.json -->\n"
    "<!-- Regenerate with: task packs:render -->\n"
    "<!-- Edit the source, not this file. Slice instead of loading the whole file: "
    "task packs:slice lessons <name> (e.g. recent --since, by-tag --tag) -->\n"
)

DOC_TITLE = "# Lessons Learned"


def render(pack: dict) -> str:
    """Render a pack object to the full meta/lessons.md projection text."""
    parts: list[str] = [BANNER, f"\n{DOC_TITLE}\n"]
    for entry in pack.get("lessons", []):
        title = entry["title"]
        body = entry["body"]
        parts.append(f"\n## {title}\n\n{body}\n")
    return "".join(parts)


def render_file(source: Path) -> str:
    """Load the pack JSON at ``source`` and return the rendered projection text."""
    if not source.is_file():
        raise FileNotFoundError(f"pack source not found: {source}")
    pack = json.loads(source.read_text(encoding="utf-8"))
    return render(pack)


def write_render(source: Path, output: Path) -> str:
    """Render ``source`` and write the projection to ``output``. Returns the text."""
    text = render_file(source)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    return text


def check_drift(source: Path, output: Path) -> tuple[bool, str, str]:
    """Compare a freshly rendered projection against the committed ``output``.

    Returns ``(has_drift, rendered, current)``. ``has_drift`` is True when the
    committed file is missing or differs from the freshly rendered text.
    """
    rendered = render_file(source)
    current = output.read_text(encoding="utf-8") if output.is_file() else ""
    return rendered != current, rendered, current


def _first_diff_line(rendered: str, current: str) -> int:
    """Return the 1-indexed line number of the first difference (0 if none)."""
    r_lines = rendered.splitlines()
    c_lines = current.splitlines()
    for i, (r, c) in enumerate(zip(r_lines, c_lines, strict=False)):
        if r != c:
            return i + 1
    if len(r_lines) != len(c_lines):
        return min(len(r_lines), len(c_lines)) + 1
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="pack_render.py",
        description="Render meta/lessons.md from the lessons-pack-0.1 source (ADR-001).",
    )
    parser.add_argument(
        "--source",
        type=Path,
        default=DEFAULT_SOURCE,
        help="Pack source JSON (default: packs/lessons/lessons-pack-0.1.json).",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="Projection output path (default: meta/lessons.md).",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Drift gate: render to a buffer and fail (exit 1) if it differs "
        "from the committed output instead of writing.",
    )
    args = parser.parse_args(argv)

    try:
        if args.check:
            has_drift, rendered, current = check_drift(args.source, args.output)
            if has_drift:
                line = _first_diff_line(rendered, current)
                print(
                    f"pack-drift: {args.output} is out of sync with {args.source} "
                    f"(first difference near line {line}). "
                    f"Run `task packs:render` to regenerate.",
                    file=sys.stderr,
                )
                return 1
            print(f"pack-drift: {args.output} is in sync with {args.source}.")
            return 0

        write_render(args.source, args.output)
        print(f"Rendered {args.output} from {args.source}")
        return 0
    except FileNotFoundError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
