#!/usr/bin/env python3
"""prd_render.py -- Export plan.narratives from specification.vbrief.json to PRD.md.

PRD.md is a read-only export artifact for stakeholder consumption.
The vBRIEF specification.vbrief.json is the authoritative source of truth.

Usage:
    python3 scripts/prd_render.py [--spec PATH] [--output PATH]

Options:
    --spec PATH     Path to specification.vbrief.json (default: vbrief/specification.vbrief.json)
    --output PATH   Path to output PRD.md (default: PRD.md)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Narrative key ordering for PRD output -- most important first.
NARRATIVE_KEY_ORDER = [
    "Overview",
    "ProblemStatement",
    "Goals",
    "UserStories",
    "Requirements",
    "SuccessMetrics",
    "Architecture",
]

BANNER = (
    "<!-- AUTO-GENERATED by task prd:render -- DO NOT EDIT -->\n"
    "<!-- Source of truth: vbrief/specification.vbrief.json -->\n"
)


def render_prd(spec_path: Path, output_path: Path) -> None:
    """Read specification.vbrief.json and write PRD.md."""
    if not spec_path.is_file():
        print(f"Error: specification file not found: {spec_path}", file=sys.stderr)
        sys.exit(1)

    with open(spec_path, encoding="utf-8") as f:
        data = json.load(f)

    plan = data.get("plan", {})
    title = plan.get("title", "Project")
    narratives = plan.get("narratives", {})

    if not narratives:
        print(f"Warning: no narratives found in {spec_path}", file=sys.stderr)

    lines: list[str] = [
        BANNER,
        f"# {title} -- Product Requirements Document\n",
    ]

    # Render ordered keys first, then any remaining keys alphabetically.
    rendered_keys: set[str] = set()
    for key in NARRATIVE_KEY_ORDER:
        if key in narratives:
            lines.append(f"## {key}\n")
            lines.append(f"{narratives[key]}\n")
            rendered_keys.add(key)

    for key in sorted(narratives.keys()):
        if key not in rendered_keys:
            lines.append(f"## {key}\n")
            lines.append(f"{narratives[key]}\n")

    lines.append(
        "---\n"
        "*This document is auto-generated from `vbrief/specification.vbrief.json` "
        "via `task prd:render`. Do not edit directly.*\n"
    )

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"PRD.md written to {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export plan.narratives from specification.vbrief.json to PRD.md"
    )
    parser.add_argument(
        "--spec",
        default="vbrief/specification.vbrief.json",
        help="Path to specification.vbrief.json",
    )
    parser.add_argument(
        "--output",
        default="PRD.md",
        help="Path to output PRD.md",
    )
    args = parser.parse_args()
    render_prd(Path(args.spec), Path(args.output))


if __name__ == "__main__":
    main()
